### ISSUE TITLE
Not all documented exceptions are shown

### ISSUE THREAD

**Issue by cmeeren** [MrJul/ReSharper.EnhancedTooltip#107]
In .NET Standard projects, only two of the three documented exceptions of `System.Net.Http.HttpClient` are shown. Specifically, the `HttpRequestException` is not shown.

Here's the tooltip:

![1](https://cloud.githubusercontent.com/assets/7766733/24298373/199a430a-10a6-11e7-87d8-c7ad70d3a8f2.PNG)

Here's the method definition from the debug symbols:

![2](https://cloud.githubusercontent.com/assets/7766733/24298374/199b0cea-10a6-11e7-82cd-62b1d21a0fa4.PNG)

**Comment by MrJul** [comment]
It seems fixed in ReSharper 2017.3 (Enhanced Tooltip asks R# for the documentation):
![image](https://user-images.githubusercontent.com/1623034/34223061-2bc04050-e5be-11e7-9bfd-8f1e867ded62.png)
