### ISSUE TITLE
Collection initialization tooltip incorrectly takes precedences

### ISSUE THREAD

**Issue by rizi** [MrJul/ReSharper.EnhancedTooltip#109]
With R# 2017.1 (EAP 8) it does work, with RTM does not work anymore, see the two pictures attached.
Working:
![working](https://cloud.githubusercontent.com/assets/796258/24651272/8318bbba-192d-11e7-841b-017819f0fda4.png)

Not working:
![notworking](https://cloud.githubusercontent.com/assets/796258/24651275/85f139c0-192d-11e7-9a5d-8ef882e9a34b.png)

**Comment by MrJul** [comment]
The constant display works in RTM for me. I think your problem is different: in the second screenshot, the displayed reference is `List.Add`, are you in a collection initializer?

**Comment by rizi** [comment]
Yes, shouldn't it also work in an initilalizer, if I hover over the constant?
Her is the code from the screenshot:

            ICollection<TimingDetail> timingDetails = new List<TimingDetail>
                                                      {
                                                          new TimingDetail(State.Initial, State.Configured, initalToConfiguredTime, TimingAssertions.DefaultInitialToConfiguredTimeSpan, false),
                                                          new TimingDetail(State.Configured, State.Assigned, configuredToAssignedTime, TimingAssertions.DefaultConfiguredToAssignedTimeSpan, true),
                                                          new TimingDetail(State.Assigned, State.Submitted, assignedToSubmittedTime, TimingAssertions.DefaultAssignedToSubmittedTimeSpan, true),
                                                          new TimingDetail(State.Submitted, State.ReAssigned, submittedToReassignedTime, TimingAssertions.DefaultSubmittedToReassignedTimeSpan, true),
                                                          new TimingDetail(State.ReAssigned, State.Resubmitted, reassignedToResubmittedTime, TimingAssertions.DefaultReassignedToResubmittedTimeSpan, true),
                                                          new TimingDetail(State.Resubmitted, State.Final, resubmittedToFinalTime, TimingAssertions.DefaultResubmittedToFinalTimeSpan, true),
                                                          new TimingDetail(State.Final, State.Archived, null, null, false),
                                                          new TimingDetail(State.Archived, null, null, null, false)
                                                      };

**Comment by MrJul** [comment]
Thanks. The problem is that the initializer reference takes precedence: anything under the initializer will always show the tooltip for `Add`. This should be changed.
