### ISSUE TITLE
What about Reshaper 9 support?

### ISSUE THREAD

**Issue by iccfish** [MrJul/ReSharper.EnhancedTooltip#11]
Resharper 9 released, but enhanced tooltip didn't come up with it. And this is a wonderful extension, so I just want to know if there was any plan to update.
Thanks for your efforts :+1:

**Comment by iccfish** [comment]
Hey buddy, I'm not mean to push you, just here for a hello and want to know the progress if possible.
Thanks....

**Comment by Huntk23** [comment]
I'm right there with iccfish. Would love to know if we are going to see this extension again?

**Comment by MrJul** [comment]
Wow, already one month, sorry about that.
It's still planned, believe me, I miss it as much as you do :)

**Comment by Huntk23** [comment]
Thanks for another update MrJul, looking forward to seeing it again!

**Comment by danyx23** [comment]
Here is another soul who would love to have this in Resharper 9 :). Thanks for making this!

**Comment by CompleteBrains** [comment]
I miss it to. Only when it absents you really understand its priceless. Thank you.

**Comment by MrJul** [comment]
Finally, working on it!

**Comment by CompleteBrains** [comment]
Good luck. Thanks.

**Comment by MrJul** [comment]
Support for ReSharper 9 in just released v2.1.3.

**Comment by CompleteBrains** [comment]
Awesome. Today is the day of EnhancedTooltip release so it's worldwide holiday and I am going to drink whiskey with Visual Studio, R# and your Extension.
Thank you.

**Comment by CompleteBrains** [comment]
It's so beautiful after the long separation. I have tears in my eyes.

**Comment by danyx23** [comment]
Awesome, thank you!
