### ISSUE TITLE
Double annotations on certain methods

### ISSUE THREAD

**Issue by MrJul** [MrJul/ReSharper.EnhancedTooltip#110]
![image](https://cloud.githubusercontent.com/assets/1623034/24653377/dfd86fc8-1935-11e7-8d4a-f32c29c1a16b.png)

**Comment by michael-damatov** [comment]
It may be caused by multiple external annotations found by R#. I think it would be OK just to ignore duplicate annotations.

Another example:
![image](https://cloud.githubusercontent.com/assets/11958365/25472642/75fb658e-2b2c-11e7-96f4-536f2cd83db9.png)

**Comment by MrJul** [comment]
No fix in Enhanced Tooltip: ReSharper 2017.2 doesn't seem to return duplicates external annotations anymore.
