### ISSUE TITLE
GammaJul.Resharper.EnhacedTooltip, Version=3.2.1.0 cannot find TT_ASSEMBLYREF token

### ISSUE THREAD

**Issue by atk9010** [MrJul/ReSharper.EnhancedTooltip#112]
![image](https://user-images.githubusercontent.com/22231488/27965857-1d9efad8-630b-11e7-8633-ba38120c6df9.png)
[ResharperProblem.docx](https://github.com/MrJul/ReSharper.EnhancedTooltip/files/1131545/ResharperProblem.docx)

I have the latest version of ReSharper & VS. Windows 10 Pro. Checked ReSharper all packages matched to Correct versions.

Issue;
With this extension, ReSharper parameter definitions are not displayed. Although It displays the overloads, null/not null in color, however, without any descriptions. If I use VS versus to ReSharper, info is displayed with the short description and it works well. With ReSharper selected and GammaJul extension installed, parameter info does not display. In addition, VS takes control over the Text Edit Font and Colors functions despite the ReSharper fact that ReSharper should have to override them.
All Intellisense settings are set accurately.

After this error;

Installed NuGet Resharper and JetBrains packages Globally. All necessary Node.Js packages are loaded and paths /dependencies set correctly for  IntelliJ and Rider. IntelliJ works fine {abviously no ReSharper dependency}
I have uninstalled and Clean reinstalled the ReSharper Ultimate complete package. When this extension is installed, IntelliSense Code assist does not display parameter detailed information. It displays the overloads, null/not null, however, without any description.
All settings are accurate.

**Comment by epodox** [comment]
I am having this same exact issue. No fix in sight. https://resharper-support.jetbrains.com/hc/en-us/community/posts/115000464624--Resharper-Not-displaying-overloads-properly Im not smart but it seems that Resharper and ET use older versions of the assembly that are not present or not registered in the GAC?

**Comment by epodox** [comment]
[InstallerLog2017-07-25T18-21-29.txt](https://github.com/MrJul/ReSharper.EnhancedTooltip/files/1175160/InstallerLog2017-07-25T18-21-29.txt)

Here is my log.

**Comment by MrJul** [comment]
Thank you for the report. I'm closing this issue as a duplicate. Please see #102 for more information.
