### ISSUE TITLE
ReSharper 2017.2 EAP 7 Compartibility

### ISSUE THREAD

**Issue by DimitarCC** [MrJul/ReSharper.EnhancedTooltip#113]
Can you make it compatible with ReSharper 2017.2 EAP? 
It seems there is major changes for the UI part of the API.

**Comment by iccfish** [comment]
Seems that jetbrains didn't provide all nuget packages to compile this extension over latest eap.

**Comment by DimitarCC** [comment]
Well it is provided. just is moved to another place. Installing nuget packages JetBrains.Platform.UIInteractive.XXXX and removing the old JetBrains.Platform.Shell reference from the project makes it to build and to work ofcource with some issues that i am not sure from where comes from.
However i do build it and it works on my side in the way i mentioned above.

**Comment by iccfish** [comment]
Does these packages installed from nuget.org? I've tried upgrade packages via nuget.org but did not success due to there's some version issues.

**Comment by DimitarCC** [comment]
yes from nuget.org. You should fix the Symbols package reference to point the new version and to remove the shell reference. the download the new packages from nuget. So to fix the dependencies first disable the dependency checks update all and then reenable dependency check and then install the new packages. they will install several others which will bring all necessary stuff.

**Comment by iccfish** [comment]
Thanks for your hint :-)

**Comment by MrJul** [comment]
Sorry, I don't usually publish anything for EAP versions (even though I'm using the EAPs myself) because there are often breaking changes from one version to another.

**Comment by rizi** [comment]
Hi @MrJul will you release a version for Resharper 2017.2, just asking because RTM has been released.

**Comment by IvanKonov** [comment]
We need to upgrade to ReSharper SDK to 2017.2 RTM.

**Comment by MrJul** [comment]
@rizi I'm working on it.

**Comment by rizi** [comment]
@MrJul thx for fast response, I really like your add-on, it makes R# so much better!

**Comment by MrJul** [comment]
Enhanced Tooltip v3.3.0 for ReSharper 2017.2 RTM is now released.
