### ISSUE TITLE
Do not capture mouse (allow editor scrolling when the cursor hovers over the tooltip)

### ISSUE THREAD

**Issue by michael-damatov** [MrJul/ReSharper.EnhancedTooltip#116]
The tooltip intercepts mouse wheel events and does not allow the editor to scroll the code. This is a big issue when the _EnhancedTooltip_ is configured to display lots of information,

**Comment by MrJul** [comment]
VS automatically tracks the mouse on the tooltip (there could be some clickable elements), unfortunately there's not much I can do here.
