### ISSUE TITLE
Does not process Multiline delimiters.

### ISSUE THREAD

**Issue by gurustron** [MrJul/ReSharper.EnhancedTooltip#117]
I have next class:

```
/// <summary>
/// Class summary
/// </summary>
public class TestClass
{
     /**
     <summary>
            Method summary
    </summary>
    */
     public static void Test(){}
}
```
With EnhancedTooltip disabled both summaries are shown, but with extension enabled i get only the first one shown. It seems that [multiline delimiters](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/delimiters-for-documentation-tags) are not supported.

**Comment by MrJul** [comment]
This syntax isn't supported by ReSharper currently (Enhanced Tooltip asks ReSharper for the XML doc, it doesn't parse it itself). I found this issue which tracks this limitation: [RSRP-337378](https://youtrack.jetbrains.com/issue/RSRP-337378).
