### ISSUE TITLE
ReSharper 2017.3 version

### ISSUE THREAD

**Issue by OmiCron07** [MrJul/ReSharper.EnhancedTooltip#118]
When for the 2017.3 version of ReSharper?

**Comment by rob8861** [comment]
same here. Thank you

**Comment by xprzemekw** [comment]
that would be much appreciated, kudos for hard work:)

**Comment by MrJul** [comment]
It's in master, expected a release soon (there's a few issues I want to close first).

**Comment by MrJul** [comment]
v3.4.0 for ReSharper 2017.3 is now released!

**Comment by rob8861** [comment]
@MrJul I just installed it and the installation completed with no errors, but I don't see any change in the appearance of intellisense. The plugin does not seem to do anything.
can anyone confirm that the plugin actually works after installing it in 2017.3?

**Comment by rob8861** [comment]
has this plugin been tested on Visual Studio 15.5.2? I tried reinstalling it and it still does not work. Nothing get colorized even though colorization is turned on in Resharper and my code is colorized.

**Comment by MrJul** [comment]
Yes, I'm using VS 15.5.2 myself with R# 2017.3 and Enhanced Tooltip v3.4 without any issues:
![image](https://user-images.githubusercontent.com/1623034/34267677-07f77d80-e67e-11e7-8495-106b37e20815.png)
Is the plugin correctly shown as installed in ReSharper's extensions?
Do you see its options in ReSharper > Options > Environment > IntelliSense > Enhanced Tooltip?

**Comment by rob8861** [comment]
Yes It does. That's why it is so weird. I am wondering if my Resharper
installation is faulty.

[image: Inline image 1]



[image: Inline image 2]

[image: Inline image 3]

**Comment by rob8861** [comment]
I uninstalled all my Resharper extensions and cleared the plugins folder in the AppData folder
Then, I uninstalled Resharper completely, rebooted  and then installed it again.
then I installed Enhanced Tooltip and it installs fine without errors and I can see it under Extensions and under Options >... > Intellisense but the tooltip do not get colorized. 
Unless there is some very weird option that messes things up, I have no clue what causes this.

**Comment by kimpenhaus** [comment]
Have you tried clearing R# Cache?
I had some strange issues within VS2017 before clearing the cache - after that all went for good.

**Comment by rob8861** [comment]
How do you clear the R# cache?

**Comment by kimpenhaus** [comment]
within an open solution go to options:

![image](https://user-images.githubusercontent.com/575109/34274612-a591b842-e699-11e7-8ec9-54310c382255.png)

hit clear caches and restart vs2017

**Comment by rob8861** [comment]
yea I tried that multiple times. No change.  :(

**Comment by rob8861** [comment]
I rolled back to the previously installed version of R#,  2017.2.1 and reinstalled ET version 3.3.0 and everything is working again.
Since upgrading to R# 2017.3, I had nothing but problems with it. Probably one of the worst releases of R#.
I also opened a ticket with R# support, since this appears to be occurring only on my machine.

**Comment by CADbloke** [comment]
I had a similar lack of success with R# 2017.3. The settings page was there, R# worked but the tooltip was un-enhanced. I rolled back to v 2017.2.2

I will try on other machines if/when I get to them which probably won't be this year.

Microsoft Visual Studio Professional 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.7.02053
Installed Version: Professional

**Comment by rob8861** [comment]
I tried installing the plugin on a different PC with R# 2017.3 and VS 2017 15.5.2 and this time I got 5 installation errors all related to some "ITextBuffer". 
The plugin still didn't work. there was no tooltip colorization.

**Comment by matkoch** [comment]
@rob8861 @CADbloke 

I think with version 2017.2 the tooltips of ReSharper got disabled by default. You need to enable them again.

**Comment by rob8861** [comment]
I don't think that's the issue. I turned it on and it still doesn't work.
The plugin has been broken since 2017.1. Some people including myself are
getting installation errors related to some ITextBuffer.
I have escalated this issue to R# support team and one of their engineer is
investigating it.

**Comment by CADbloke** [comment]
I f you have layers of settings try turning them on / off. Then try (after making a copy) a bisect exercise on each settings file - delete/comment-out half of the settings in the file and see what happens, the feedback is instant but you should be aware that R# caches settings files so a VS restart may be safer.

I found a setting which killed it for me
```xml
<s:Boolean x:Key="/Default/Environment/Editor/QuickInfo/EnableQuickInfo/@EntryValue">True</s:Boolean>
```
It's still not 100% for me but it's back

**Comment by IvanKonov** [comment]
@CADbloke, where are the configuration files?

**Comment by CADbloke** [comment]
R# config filles can be found via R#’s manage settings menu. In the dialogue with the settings layers there is an option on each to open the folder where the file is. I think. I don’t have Resharper on my phone. Yet.

**Comment by ajryan** [comment]
Same setting broke it for me as @CADbloke said here https://github.com/MrJul/ReSharper.EnhancedTooltip/issues/118#issuecomment-364644582

Editing my computer-level settings, changing EnableQuickInfo to false, and the suspending/resuming ReSharper fixed it.

**Comment by michael-damatov** [comment]
Solved the issue by installing the _ReSharper C++_ that was previously skipped.
