### ISSUE TITLE
Font for <c> element</c> color is dark blue on dark theme

### ISSUE THREAD

**Issue by CADbloke** [MrJul/ReSharper.EnhancedTooltip#12]
![vs-enhancedtooltipbluetext](https://cloud.githubusercontent.com/assets/147329/5833593/ffdb239e-a1a8-11e4-904f-3ec361817fb3.png)
See Screengrab. Doc Comment text between `<c></c>` tags is dark blue and hard to read. Is this dependent on a Visual Studio 2013 color setting?

VS 2013 + R# 8.2.3 Dark theme

btw, the R# Extension Manager says "There are problems with this Extension" on every machine I have it on (4-5 of them). It hasn't given me any problems so I don't know what that's all about.

Nice extension btw - thanks for writing it.

Here is the doc comment to save you some typing...

````csharp
    /// <summary>
    /// Gets a value indicating whether the global IsDebugEnabled should be overriden.
    /// 
    /// <para/>
    /// 
    ///             Note that this value will override all settings of each listener globally. If this value is
    ///             set to <c>null</c>, nothing will be overriden.
    /// 
    /// </summary>
    /// 
    /// <value>
    /// <c>true</c> if debug logging must be enabled for all log listeners; otherwise, <c>false</c>.
    /// </value>
    public static bool? IsDebugEnabled
    {
      get
      {
        return LogManager._isDebugEnabled;
      }
      set
      {
        LogManager._isDebugEnabled = value;
        LogManager.LogInfo.UpdateLogInfo();
      }
    }
````

**Comment by MrJul** [comment]
ReSharper has some built-in property when rendering colored text to auto-adjust the contrast in order to avoid this problem. However, I'm already setting it currently, I'll investigate as to why it's not being applied.

Does ReSharper tell you more about the "problem" with this extension?

**Comment by MrJul** [comment]
Fixed in v2.1.3, please update.

**Comment by CADbloke** [comment]
Thanks for fixing this, confirmed that it works on my PC. 

Here is a screengrab of the R# warning about problems with the extension (of which I have had none, apart from the blue words you just fixed).

![rs-enhancedtooltipwutproblems](https://cloud.githubusercontent.com/assets/147329/5993731/cc71e160-aaad-11e4-91b9-01222f47b52b.png)

There is, of course, no "Additional Information" to click. I'm using R# 8.2.3

**Comment by MrJul** [comment]
In ReSharper 8.2, Enhanced Tooltip silently installs an additional VS extension to work, that might be the cause of the issue. If you have some time, try to run VS with the ''/ReSharper.Internal'' switch and see if some exceptions are displayed.

In ReSharper 9.0, due to changes in the registration process, this is not needed anymore.

**Comment by CADbloke** [comment]
I found the ReSharper Exception browser, there were no errors in there caused by your extension.
