### ISSUE TITLE
hints do not work in 2017.3.1

### ISSUE THREAD

**Issue by IvanKonov** [MrJul/ReSharper.EnhancedTooltip#122]
![image](https://user-images.githubusercontent.com/20556427/34784334-067da29c-f63f-11e7-83d9-1fd072ea6d07.png)

![image](https://user-images.githubusercontent.com/20556427/34784205-b55ccd8e-f63e-11e7-9af1-a5a03ab28c5f.png)
![image](https://user-images.githubusercontent.com/20556427/34784252-d227a182-f63e-11e7-8f8d-2ee8a64804c2.png)
![image](https://user-images.githubusercontent.com/20556427/34784287-eafda3fa-f63e-11e7-8698-092d22663c89.png)

**Comment by Protoster** [comment]
I am also having this issue in the same version of resharper. I've observed further strange behavior. If I uncheck the "Enhance identifier tooltips" option, this is what I see:
![image](https://user-images.githubusercontent.com/5383872/35053522-4a159b52-fb78-11e7-8133-36498f270f02.png)

The tooltip is displayed twice.

**Comment by RogerUP13** [comment]
I also have this issue

**Comment by xprzemekw** [comment]
Does not work either unfortunately.  VS 2017 15.5.4, R# 2017.3.1.

**Comment by CADbloke** [comment]
I'm getting the same behaviour as @Protoster in VS 2017.5.6, R# 2017.3.2

**Comment by CADbloke** [comment]
I think there is a problem with settings. See https://github.com/MrJul/ReSharper.EnhancedTooltip/issues/118#issuecomment-364644582

I have the same behavior as @Protoster, even after wiping all of R# caches and any mention of the old plugin..

It is also omitting the `<remarks>` part of the XML doc comment.. I'm hoping #123 is the problem.

**Comment by IvanKonov** [comment]
After the last update, hints still do not work

**Comment by IvanKonov** [comment]
For those who have a problem, just install Resharper C++.
#126
