### ISSUE TITLE
Both Visual Studio and Enhanced tooltips

### ISSUE THREAD

**Issue by busyscout** [MrJul/ReSharper.EnhancedTooltip#124]
VS2017. After plugin installation all visual studio tooltips are still in place. They are not replaced, they show with new ones from this plugin. Now I have 3 types of tooltips at the same time (depends on mouse position) - from VS, from Resharper and from this plugin. Is it OK?

**Comment by busyscout** [comment]
![tooltip 1](https://user-images.githubusercontent.com/23096209/36285384-624e44e8-12bc-11e8-99ad-34103da54673.png)
![tooltip 2](https://user-images.githubusercontent.com/23096209/36285386-6604b0cc-12bc-11e8-9934-af511feb4196.png)

**Comment by busyscout** [comment]
If I uncheck "Enhance identifier tooltips" in options everything works OK.

**Comment by jnothstine** [comment]
I am also having problems related to "Enhance identifier tooltips"  If I check that box then nothing wht Enhanced Tooltip works.  If I uncheck the box then the items under "Display" options (spcifically, Limit tooltip width...) works.  When the "Enhance identifier tooltips" is selected, that doesn't even work.

I can't get this plugin to work correctly at all.  I do have the "Replace Visual Studio tooltip" checkbox in Editor Appearance check.  I also have "Color identifiers" selected in Code Inspection\Settings.

Not sure what to do to get this plugin to work but it sure would be nice if I could.

**Comment by MrJul** [comment]
Can you please try Enhanced Tooltip v3.6.0 with ReSharper 2018.1?
I've fixed an issue where ReSharper C++ was incorrectly needed (otherwise the plugin was failing in various ways).

**Comment by evil84** [comment]
v3.6.0 with ReShaper 2018.1, every c# feature works OK, but c++ tooltip was GONE. can u fix it plz, thank u.

**Comment by MrJul** [comment]
C++ tooltips are fixed in v3.7.0.
