### ISSUE TITLE
Colorization of descriptive text unreadable after install of VS2017 version 15.6

### ISSUE THREAD

**Issue by NW7US** [MrJul/ReSharper.EnhancedTooltip#125]
After installing VS2017 Enterprise update to version 15.6, on March 6, 2018, color setting issues occur.

When an EnhancedTooltip pops up, the textual description (like the <summary> section of the comments of a method) no longer is a lighter, easy-to-read-against-black font color.  Now, it is black on black, where the background is only slightly lighter than the black text.  I cannot find a setting to change this.

**Comment by MrJul** [comment]
Obviously, something has changed in VS, I need to investigate...

**Comment by gaspardip** [comment]
This was driving me crazy, I thought I changed some setting on accident. I even repaired my install

**Comment by CADbloke** [comment]
R# 2017.3.3 has the "Disaster Area" look and feel in VS 15.6.1. Still that may just be the random nature of things talking.

Is it just me or is the enable option inverted? I un-tick "Enhance Identifier Tooltips" and all the extras are turned on, tick it and I'm back to standard Visual Studio tooltips.

**Comment by garyng** [comment]
Same here...

With Enhanced Tooltip enabled
![image](https://user-images.githubusercontent.com/4453664/37339207-d868bf72-26f4-11e8-82e3-764a02ffa0b3.png)

With Enhanced Tooltip disabled
![image](https://user-images.githubusercontent.com/4453664/37339230-f052c60a-26f4-11e8-80c3-f20e2ab763c8.png)

With ReSharper disabled
![image](https://user-images.githubusercontent.com/4453664/37339287-2bd87b48-26f5-11e8-8e9f-f28ccbb435ba.png)

**Comment by farzadmf** [comment]
Same issue here. For me, it's even worse . Maybe because I have the Solarized theme enabled using color theme editor

![image](https://user-images.githubusercontent.com/5768792/37409394-a398ad0e-2774-11e8-9091-49e9e404669f.png)

**Comment by NW7US** [comment]
I've now updated to the latest VS 2017 update ("Microsoft Visual Studio Enterprise 2017, Version 15.6.2"). 

I'm using the latest ReSharper, etc.

The issue presents itself in my environment nearly identical to the examples shown by garyng.  

Has anyone dug underneath to see what is configurable?  I've gone through all of the Font and Colors entries and see nothing that correlates with this enhanced tooltip.

I barely can live without this amazing tool.  But, my eyes are going crazy bad with this current issue.

There are some other issues, too.  I'll start another post.

**Comment by CADbloke** [comment]
On VS 15.6.2 + R# 2017.3.3 it makes no difference whether I enable Enhanced Tooltips or not, only disabling Resharper will stop it. This is the color scheme I use, hence the "[Disaster Area](http://hitchhikersguidequotes.tumblr.com/post/14488089401/its-the-wild-colour-scheme-that-freaks-me-out)" reference in my last comment.

![vs15 6 2-rs2017 3 3-ett-enabled](https://user-images.githubusercontent.com/147329/37434597-33e59cb8-2834-11e8-92c2-40875b064cfe.png)

**Comment by MrJul** [comment]
It turns out the tooltip visual hierarchy has changed: Microsoft has rewritten it in VS15.6.
To be honest, it was unnecessary complicated before.

I've fixed it, but I need to polish the fix a bit before I can release it, to avoid breaking the tooltip on older VS versions.

**Comment by NW7US** [comment]
Awesome!  You rock.  

Incidentally, will there ever be a way for us to configure the color scheme (or is there now a way, but I cannot figure it out)?

**Comment by garyng** [comment]
@NW7US I guess the tooltip will follow your Visual Studio’s colour scheme?

**Comment by MrJul** [comment]
@NW7US Yes, what @garyng say, it follows your color scheme in Fonts&Colors. It uses additional ReSharper coloring if you've enabled "color identifiers" in ReSharper options.

**Comment by MrJul** [comment]
This is fixed in v3.5.0 now available.

**Comment by TAGC** [comment]
Looks awesome again!

![2018-03-19_13-34-48](https://user-images.githubusercontent.com/1588951/37598611-9a788c26-2b7a-11e8-97a0-dd4f1683b5c2.png)

**Comment by NW7US** [comment]
How do I get my ReSharper extension manager to see the new version?  I still only see version 3.3.0.

**Comment by NW7US** [comment]
I'm updating to the latest ReSharper -- perhaps the newest version of this EnhancedTooltip will appear, now.

**Comment by NW7US** [comment]
Updating my ReSharper fixed the Extension Manager, so I now have the latest EnhancedToolip.  It works GREAT!  Fabulous!  It is incredibly useful for me.  Thank you.
