### ISSUE TITLE
R# 2018.1 supported

### ISSUE THREAD

**Issue by rizi** [MrJul/ReSharper.EnhancedTooltip#129]
Hi, is the latest version compatible with R# 2018.1 or do you have to create a new version?

thx in advance

**Comment by dojo90** [comment]
+1

**Comment by MrJul** [comment]
I have to release a new version.
I'm currently working on it (there are breaking changes).

**Comment by MrJul** [comment]
Enhanced Tooltip v3.6.0 with ReSharper 2018.1 support is out!
