### ISSUE TITLE
Support for R# 2018.2

### ISSUE THREAD

**Issue by RogerUP13** [MrJul/ReSharper.EnhancedTooltip#136]
Hello. Could you please make this extension compatible with R# 2018.2?

**Comment by robfazio** [comment]
any ETA?

Thanks,

**Comment by IneedHelp** [comment]
+1, please update the extension, it's pretty much the most useful ReSharper extension

**Comment by IneedHelp** [comment]
I miss this extension so much, I'd update it myself if I knew how..

**Comment by DimitarCC** [comment]
well i upgraded it but it have issues :(

**Comment by DimitarCC** [comment]
Well it seems one of the problems is actually a Resharper bug. So i can say that my conversion were successful :)
If anyone wants to try it out before MrJul to fix it officially can contact me about that. ;)

**Comment by robfazio** [comment]
what bug? I spoke to them about this plugin and they told me they intend to fix the issue in 2018.2.2

**Comment by DimitarCC** [comment]
@robfazio  look at this https://youtrack.jetbrains.com/issue/RSRP-471266
The main problem is that it not show some elements in resharper tooltip at all so therefore it can not be handled by ET

**Comment by xprzemekw** [comment]
@DimitarCC  Did you build from sources?

**Comment by DimitarCC** [comment]
@xprzemekw Ibuilt ET from latest source but modify it to make it compatible with resharper 2018.2 and fixed some other issues in display that came because of latest changes in VS and Resharper

**Comment by robfazio** [comment]
I asked Resharper if they can take over this plugin since it is no longer being supported by the author and they said no. 
I honestly don't understand why they can't improve their own ugly looking tool-tip. Clearly the author did the job for them already. All they have to do is merge it to their code base. oh well

**Comment by MrJul** [comment]
Hello all. I'm still supporting the plugin (and wil continue to do so) but I'm on vacations currently and posting this from my phone. Expect an update in like 10 days (ETA not contractually guaranteed :p)

**Comment by robfazio** [comment]
@MrJul very much appreciated .
Sorry if It came out as snarky, clearly you doing it on your own free time and it is much appreciated. I was just wondering why Reharper never made your plugin official since I honestly think it is the most popular but I could be wrong, :)

enjoy your vacation.

p.s: It seems like they fixed the ITextBuffer bug in 2018.2.2

**Comment by IneedHelp** [comment]
I don't mean to undermine this plugin which I absolutely love, but not being able to live without it I found an alternative in https://github.com/wmjordan/Codist

**Comment by robfazio** [comment]
> ReSpeller was also a separate ReSharper plugin which they've merged into ReSharper, guess illiterate people are a more pressing issue ;D

dey totali hev der prioritis wrong wen it comes to illiterate people :-D

**Comment by DimitarCC** [comment]
> I don't mean to undermine this plugin which I absolutely love, but not being able to live without it I found an alternative in https://github.com/wmjordan/Codist

Well that is indeed a potential alternative but it lack features and is totally text one. ET on other hand is is very good designed and you can easily understand what is issue, what is suggestion and what is error.
This can not happen with Codist

**Comment by DimitarCC** [comment]
> p.s: It seems like they fixed the ITextBuffer bug in 2018.2.2

@robfazio There is not yet official 2018.2.2 nor a preview. The latest official is 2018.2.1 ;)

**Comment by DimitarCC** [comment]
@MrJul Yes we do understand it. But i think you need a bit help with it. Also i think you should drop the support of old visual studio and keep only VSSDK 15 support. That will give you opportunity to use the new async tooltips that VSSDK 15 supports ;)

**Comment by xprzemekw** [comment]
@MrJul  your work is much appreciated, happy holidays and thx for great work!

**Comment by IneedHelp** [comment]
Life is sad without this extension..

**Comment by RogerUP13** [comment]
@MrJul thank you for the answer. I'm looking forward for the update.

**Comment by dsaf** [comment]
I feel blind without this extension.

**Comment by IneedHelp** [comment]
4-5 more days to wait

**Comment by MrJul** [comment]
I'm working on it right now.

The initial integration works if anyone wants to build from the current master, but I still have to fix #135 properly first before releasing.

**Comment by robfazio** [comment]
sweet man. Take your time. Don't rush it :)
We always appreciate your time and dedication. 

Merci

**Comment by MrJul** [comment]
Enhanced Tooltip v3.7.0 compatible with ReSharper 2018.2 and Visual Studio 15.8 is now available!
