### ISSUE TITLE
Show null reference state for parameters and locals

### ISSUE THREAD

**Issue by michael-damatov** [MrJul/ReSharper.EnhancedTooltip#137]
The ReSharper control flow engine already tracks the _null reference_ state. It would be nice to see the _current_ state at the mouse cursor.

As far as I know the following states are tracked:
* null
* not null
* true
* false
* unknown

**Comment by michael-damatov** [comment]
Visual Studio 2019 already shows this:

![image](https://user-images.githubusercontent.com/11958365/80402228-e88d6b00-88bd-11ea-87a9-1730689c4bc1.png)

It would be nice to show it as well.

**Comment by michael-damatov** [comment]
Any update on this issue?

**Comment by DimitarCC** [comment]
Yes. I added that display in latest version of the Enhanced tooltip. But to make it really display you have to disable replacing of visual studio tooltips.

![image](https://github.com/MrJul/ReSharper.EnhancedTooltip/assets/1904901/1eccefc0-cf6f-461f-baf1-774e1ca698d8)

Maybe there can be more elegant solution that i will search for in future but for now the display is there.
