### ISSUE TITLE
Add ReSharper 2019.1 support

### ISSUE THREAD

**Issue by OmiCron07** [MrJul/ReSharper.EnhancedTooltip#142]

**Comment by DimitarCC** [comment]
well 2019.1 seems to be still buggy.... At least for me the code analysis takes ages on large files. Otherwise i were managed to build Enhanced tooltip for 2019.1 and seems there is no problems with the plugin itself.

**Comment by MrJul** [comment]
Pre-release version 3.9.0 is now available for ReSharper 2019.1-eap04.
I'm leaving this issue open, and will close it when ReSharper 2019.1 RTMs.

**Comment by MrJul** [comment]
I'm closing this since I had to update the SDK for EAP 7.
I'll create a new issue once 2019.1 hits RTM.

**Comment by FutureTD** [comment]
I see you have fixed this bug, Is this version available to be used in resharper? If so how can I use it.
