### ISSUE TITLE
Support VS2019 semantic coloring

### ISSUE THREAD

**Issue by MrJul** [MrJul/ReSharper.EnhancedTooltip#144]

**Comment by silkfire** [comment]
@MrJul How do you enable semantic coloring on the tooltip?

**Comment by MrJul** [comment]
@silkfire Nothing special to do, just configure the new User Members colors in Visual Studio 2019, Enhanced Tooltip will pick them up.

![image](https://user-images.githubusercontent.com/1623034/57191638-1698d300-6f28-11e9-8495-fca645ab150c.png)

**Comment by silkfire** [comment]
@MrJul Awesome, much appreciated :)
