### ISSUE TITLE
Display base class for Type parameters 

### ISSUE THREAD

**Issue by silkfire** [MrJul/ReSharper.EnhancedTooltip#145]
ET doesn't seem to show the constrained-to base class when hovering over a type parameter.  It _does_ if the type parameter is constrained to an interface, though.

So I want this:

![typeparameter-base](https://user-images.githubusercontent.com/1554615/56284373-97786200-6114-11e9-8994-f688989224b5.png)

to be displayed like this:

![typeparameter-interface](https://user-images.githubusercontent.com/1554615/56284395-a0693380-6114-11e9-8653-2bf974507858.png)

but with an **[Inherits]** marker.

**Comment by MrJul** [comment]
Good catch! I'll fix it.

**Comment by silkfire** [comment]
@MrJul Not sure if it's related, but latest version `3.8.0 `no longer shows when a class inherits another one.

![ET](https://user-images.githubusercontent.com/1554615/56724994-51428480-674c-11e9-97a0-4f6005026caa.png)

**Comment by silkfire** [comment]
@MrJul Oh I just checked and it still doesn't seem to work...

![ET2](https://user-images.githubusercontent.com/1554615/56726141-8354e600-674e-11e9-80ce-578a4d519725.png)

**Comment by MrJul** [comment]
For the issue where you have no base class at all please ensure the "show the base class" option is correctly set in Enhanced Tooltip's option page.

Regarding the type parameter's constraint‚ it's fixed in v3.10.0 (only available for ReSharper 2019.1-eap07).

**Comment by GabrielBBF** [comment]
@MrJul Awesome. Thanks for the solutions and the quick response.

**Comment by silkfire** [comment]
Awesome. Thanks for the solutions and the quick response.
