### ISSUE TITLE
2019.2 eap4 - the usual shifting of the goalposts so it won't install

### ISSUE THREAD

**Issue by CADbloke** [MrJul/ReSharper.EnhancedTooltip#148]
I had a few stabs at getting the latest version running in R# 2019.2.eap4  but it appears they have changed an API. Well, we could at least pretend to be surprised. 

```
--- EXCEPTION #1/2 [MissingFieldException]
Message = “Field not found: 'JetBrains.ReSharper.Psi.CSharp.CSharpLanguage.Instance'.”
```
https://youtrack.jetbrains.com/issue/DEXP-474165 is for eap3 but eap behaved the same.

**Comment by matkoch** [comment]
Hi @CADbloke, I just want to give some information on this. Syntax-wise, it is not a breaking change (field became property), but plugins are subject to recompilation for new major versions anyways. This particular change was done for migration to .NET Core. I can assure you, we don't do breaking changes easily or to annoy anyone :) Actually, I'm also maintaining quite a few plugins and face these situations by a multiple. If you need any help, feel free to reach out to me.

**Comment by CADbloke** [comment]
@matkoch Thanks for the update and the offer of assistance. 

Sadly I don’t have the headspace or bandwidth to fork this and update it, I wish I did. I looked at a couple of past updates and they involved a lot more than just changing the references and recompiling, I don’t know this package or R# well enough to to it properly.

**Comment by mvonballmo** [comment]
2019.2 has been released and the API should be stable again. Is there anyone familiar with the codebase/R# extensions who can upgrade to the latest SDK and release a version?

Or maybe someone can give me a hint on what needs to be done to produce a release? I can see some build files, but am not sure how to upgrade the SDK, etc. Is it just the upgrade for the `JetBrains.ReSharper.SDK` package?

**Comment by DimitarCC** [comment]
i have a version that installs on 2019.2. If anyone want it till is officially, released let me know.

**Comment by OmiCron07** [comment]
@DimitarCC Yes, shoot!

**Comment by DimitarCC** [comment]
Well then here is the nuget package than you have to load from local plugin repo.

[JLebosquain.EnhancedTooltip.3.10.2.zip](https://github.com/MrJul/ReSharper.EnhancedTooltip/files/3559625/JLebosquain.EnhancedTooltip.3.10.2.zip)

**Comment by MrJul** [comment]
v3.11.0 with support for R# 2019.2 is now available.

**Comment by DimitarCC** [comment]
Well still not in the feed ;)

**Comment by MrJul** [comment]
It's pushed, but it has to be validated by JetBrains before appearing (usually a couple of days).
