### ISSUE TITLE
Support for R# 2019.2

### ISSUE THREAD

**Issue by mu88** [MrJul/ReSharper.EnhancedTooltip#149]
Hi! Could you please make this extension compatible with R# 2019.2? I'd highly appreciate :smiley:

**Comment by MrJul** [comment]
I was on holidays, I'm planning to add support for R# 2019.2 this weekend.

**Comment by MrJul** [comment]
Late, but v3.11.0 with support for R# 2019.2 is now available!

**Comment by FutureTD** [comment]
I am not seeing the new update in extension list, has it been added already?

**Comment by OmiCron07** [comment]
https://github.com/MrJul/ReSharper.EnhancedTooltip/issues/148#issuecomment-530349461
