### ISSUE TITLE
Support typeparam and typeparamref

### ISSUE THREAD

**Issue by luedi** [MrJul/ReSharper.EnhancedTooltip#151]
I found that the tags `<typeparam name= "" />` and `<see typeparamref="" />` are not supported:
![image](https://user-images.githubusercontent.com/12098314/67561722-a83a0e00-f71d-11e9-8256-5bac9bcb8306.png)
I would be glad if you could enhance the addin to support these tags.
Best Regards
Klaus

**Comment by DimitarCC** [comment]
Added in latest version ;)
