### ISSUE TITLE
Support for R# 2019.3

### ISSUE THREAD

**Issue by rizi** [MrJul/ReSharper.EnhancedTooltip#152]
Hi! Could you please make this extension compatible with R# 2019.3?

br

**Comment by MrJul** [comment]
It's pushed! Please wait a couple day for JetBrains to approve it.

**Comment by derigel23** [comment]
@MrJul how was you able to update SDK to 2019.3 version? It's broken :)

**Comment by MrJul** [comment]
Using some magic apparently :)
I don't know, everything restored correctly, I didn't have any problems?
