### ISSUE TITLE
Support Nullable Reference Types

### ISSUE THREAD

**Issue by michael-damatov** [MrJul/ReSharper.EnhancedTooltip#154]
Please add support for nullable reference types:

Consider the following variable declaration: 

``` csharp
Func<int, string?> keySelector = i => i > 0 ? "ok" : null;
```
Currently, the tooltip ignores the nullable annotation:
![image](https://user-images.githubusercontent.com/11958365/72218749-b8a09e80-353e-11ea-951a-67112a1a57a5.png)

**Comment by mronnblom-cint** [comment]
Also, when Nullable Reference Types is enabled, the default tooltip for variables contains info about the nullability:
'foo' is not null here.
'foo' may be null here.

That would be nice to have in this extension as well.

**Comment by michael-damatov** [comment]
@mronnblom-cint see my feature request at #137
