### ISSUE TITLE
Support Resharper 2020.1 (with bonus dodgy fix)

### ISSUE THREAD

**Issue by CADbloke** [MrJul/ReSharper.EnhancedTooltip#157]
I think I made it work but I'm also willing to be it's a bit rough and wrong. Works on my machine [TM]. Here's what a pull request would look like if it was done by an idiot...

### `GammaJul.ReSharper.EnhancedTooltip.csproj`
```xml
<Project Sdk="MSBuild.Sdk.Extras/1.6.68">

	<PropertyGroup>
		<AssemblyName>GammaJul.ReSharper.EnhancedTooltip</AssemblyName>
		<RootNamespace>GammaJul.ReSharper.EnhancedTooltip</RootNamespace>
		<TargetFramework>net461</TargetFramework>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<MSBuildWarningsAsMessages>MSB3277</MSBuildWarningsAsMessages>
		<OutputPath>..\..\output\$(Configuration)</OutputPath>
		<LangVersion>7.3</LangVersion>
		<ExtrasEnableWpfProjectSetup>true</ExtrasEnableWpfProjectSetup>
	</PropertyGroup>
	
	<ItemGroup>
		<Reference Include="System.Windows.Forms" />
	</ItemGroup>

	<ItemGroup>
		<!-- Obtain version from https://api.nuget.org/v3/flatcontainer/jetbrains.platform.visualstudio/index.json -->
		<PackageReference Include="EnvDTE" Version="8.0.0" />
		<PackageReference Include="JetBrains.Annotations" Version="2020.1.0" />
		<PackageReference Include="JetBrains.Lifetimes" Version="2020.1.3" />
		<PackageReference Include="JetBrains.ReSharper.SDK" Version="2020.1.0">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="VSSDK.Editor" Version="11.0.*" />
		<PackageReference Include="VSSDK.Language" Version="11.0.*" />
		<PackageReference Include="VSSDK.Shell.Immutable.11" Version="11.0.*" />
		<PackageReference Include="VSSDK.Text" Version="11.0.*" />
		<PackageReference Include="NuGet.CommandLine" Version="4.6.2" />
	</ItemGroup>

</Project>
```
The `CSPROJ` updates are via Nuget packages. I had to hunt for `JetBrains.Lifetimes` in my local cache after a Nuget update conflict told me to install it separately but of course it isn't available separately because Kafka was right. No idea why `JetBrains.Annotations` wanted to join the party but as Freud said*, "knowing why is the booby-prize" [*he may not have said that].

### `CSharpColorizer.cs`
added a reference for  `using JetBrains.Metadata.Reader.API;`, ended up on line 10 in mine by YMMV
[Line 229](https://github.com/MrJul/ReSharper.EnhancedTooltip/blob/master/source/GammaJul.ReSharper.EnhancedTooltip/Presentation/CSharpColorizer.cs#L229) *which becomes line 230* changed from 
```csharp
if (element.IsRefReturnMember() || (element is ICSharpLocalVariable localVariable && localVariable.Kind.IsByReference()))
```
to
```csharp
if (element.IsRefReturnMember() || (element is ICSharpLocalVariable localVariable && localVariable.ReferenceKind.IsByReference()))
```
which is, in all likelihood, a mistake but it fixed the build. Whether it works or not....

The only guarantee with this is if it crashes VS on you, you'll hate me. Good luck! **STAY AT HOME**

**Comment by MrJul** [comment]
I'm currently updating Enhanced Tooltip to work with ReSharper 2020.1, thanks for your contribution!

You can't do a simple NuGet update because `JetBrains.Platform.VisualStudio` is an unlisted package. Get the latest version, modify the .csproj manually accordingly, and voila :) See https://github.com/MrJul/ReSharper.EnhancedTooltip/commit/eaf0d589974350c3511c91940e6f04c1a618f179#diff-67d25278046ab543a511c22807ca6a9dL23

Regarding the `ReferenceKind` change, it looks correct to me.

**Comment by Aldaviva** [comment]
Thank you for all the hard work, @MrJul, @CADbloke, and other contributors. I'm surprised by how quickly you add support for new ReSharper versions. This is a great extension and it's very appreciated.
