### ISSUE TITLE
Errors During 2020.1 Install.

### ISSUE THREAD

**Issue by Mike-E-wins** [MrJul/ReSharper.EnhancedTooltip#158]
FWIW I encountered the following errors while installing 2020.1:

```
12:38:35.271 |E| Error resolving type JetBrains.Lifetimes.Lifetime from assembly “JetBrains.Platform.RdCore, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”, request originating from assembly “GammaJul.ReSharper.EnhancedTooltip, Version=3.9.0.0, Culture=neutral, PublicKeyToken=null”. Could not find a referenced assembly by the TT_ASSEMBLYREF token.
12:38:35.361 |E| Error resolving type JetBrains.Lifetimes.Lifetime from assembly “JetBrains.Platform.RdCore, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”, request originating from assembly “GammaJul.ReSharper.EnhancedTooltip, Version=3.9.0.0, Culture=neutral, PublicKeyToken=null”. Could not find a referenced assembly by the TT_ASSEMBLYREF token.
12:38:35.370 |E| Error resolving type JetBrains.Lifetimes.Lifetime from assembly “JetBrains.Platform.RdCore, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”, request originating from assembly “GammaJul.ReSharper.EnhancedTooltip, Version=3.9.0.0, Culture=neutral, PublicKeyToken=null”. Could not find a referenced assembly by the TT_ASSEMBLYREF token.

```

I have also reported this here:
https://youtrack.jetbrains.com/issue/RSRP-479293

**Comment by CADbloke** [comment]
my bodge at #157 might help. Or not.

**Comment by GvmiHasan** [comment]
> my bodge at #157 might help. Or not.
> 
> > I had to hunt for JetBrains.Lifetimes in my local cache after a Nuget update conflict told me to install it separately but of course it isn't available separately because Kafka was right.

Hi,
Can you release your own solution in something executable (without needing any compilation) worst thing of resharper is this compatibility corruption on each new release version!

**Comment by CADbloke** [comment]
Here it is. remove the `.zip` from the end of the file name, add the path you put it in to the Extension manager paths list in Resharper's options. This works on my Win 10 VS 16.5.4 but I make no guarantees, this is a file from a stranger on the Internet, remember.
[jlebosquain.enhancedtooltip.3.99-v2020 .nupkg.zip](https://github.com/MrJul/ReSharper.EnhancedTooltip/files/4534422/jlebosquain.enhancedtooltip.3.99-v2020.nupkg.zip)

**Comment by GvmiHasan** [comment]
> Here it is. remove the `.zip` from the end of the file name, add the path you put it in to the Extension manager paths list in Resharper's options. This works on my Win 10 VS 16.5.4 but I make no guarantees, this is a file from a stranger on the Internet, remember.
> [jlebosquain.enhancedtooltip.3.99-v2020 .nupkg.zip](https://github.com/MrJul/ReSharper.EnhancedTooltip/files/4534422/jlebosquain.enhancedtooltip.3.99-v2020.nupkg.zip)

Alright, Alright, Alright... It worked well 👍 Now i can write my professional `Console.WriteLine("Hello, Woooorld");` again! Thank's man 😊

**Comment by MrJul** [comment]
Enhanced Tooltip 3.13 for ReSharper 2020.1 has been released.
It should be available in a couple days (it's pending JetBrains' approval).

Feel free to reopen this issue if you've got installation problems with it.
