### ISSUE TITLE
RTL language comments

### ISSUE THREAD

**Issue by emdadgar2** [MrJul/ReSharper.EnhancedTooltip#16]
Dear MrJul!
Is there any chance to render RTL languages in correct way?

**Comment by MrJul** [comment]
Sure, could you get a screenshot explaining what's wrong? I'm using standard controls which should support RTL. Are RTL languages displayed correctly in ReSharper's tooltip without EnhancedTooltip?

**Comment by MrJul** [comment]
@emdadgar2 Could you please provide more information about this issue?
I'm not used to RTL languages.

**Comment by MrJul** [comment]
I'm closing this since I need more information. Reopen if needed.
