### ISSUE TITLE
Please add support for ReSharper 2021.1 - RTM

### ISSUE THREAD

**Issue by rizi** [MrJul/ReSharper.EnhancedTooltip#165]
Hi,
Today R# 2021.1 RTM has been released, would you be so kind and add support for it.

br

**Comment by zeldafreak** [comment]
PSA: Like last time, you can work around this by installing ReSharper v2020.3.2 from JetBrains' [Previous Releases](https://www.jetbrains.com/resharper/download/previous.html) pages until the extension is updated.

**Comment by MrJul** [comment]
Enhanced Tooltip v3.16 has been released, compatible with ReSharper v2021.1.2! (It's pending JetBrains approval.)
