### ISSUE TITLE
ReSharper 2021.2 support

### ISSUE THREAD

**Issue by NN---** [MrJul/ReSharper.EnhancedTooltip#166]

**Comment by rizi** [comment]
Would be great if support will be added, R# 2021.2 RTM has been released today.
Br

**Comment by Mike-E-angelo** [comment]
It appears to be listed, but when installed, it leads to the exceptions reported here:
https://youtrack.jetbrains.com/issue/RSRP-485494

**Comment by DimitarCC** [comment]
Any news about  ReSharper 2021.2 support?? Seems there are many changes. @MrJul are you working on it?

**Comment by matkoch** [comment]
Hi @MrJul!

My attempt to upgrade here (not tested): https://github.com/matkoch/ReSharper.EnhancedTooltip/commit/c583462cacf33fad9d53a90e6f09cc61d3dede23

And besides, my offer to take over maintenance still stands :)

**Comment by pedoc** [comment]
@matkoch not working with 2022 preview 3

**Comment by DimitarCC** [comment]
@pedoc its working. I am using it on preview 3.

Вземете Outlook за Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by pedoc** [comment]
@matkoch first,thank you for your work.

The problem I encountered is that Resharper 2021.2 installed on the vs2019 preview version 4.0, through offline installation of the plug-in, and the generated nupkg cannot be seen in the extension manager

**Comment by MudbootsTheDeveloper** [comment]
In fact, this plugin is so crucial to my development process that I'm suspending R# update till the new version of the plugin comes out.

**Comment by DimitarCC** [comment]
Well if someone is too eager to use that is vs2022 preview or with 2021.3 EAP i have a package that is installable from local repo and it works just fine. I am using it with VS2022 Preview 6 and R# 2021.3 EAP 4.

**Comment by rizi** [comment]
> > @DimitarCC thx, would be great if you share your package for VS 2022, could you tell me how to use a local repo for your package. Can I just a folder on my hard drive that contains all local packages? br
> 
> [JLebosquain.EnhancedTooltip.3.18.0.zip](https://github.com/MrJul/ReSharper.EnhancedTooltip/files/7382031/JLebosquain.EnhancedTooltip.3.18.0.zip) This is the package. Unzip it and put nupkg file somewhere in empty folder on your harddrive and then in resharper options add a new extensions source ![image](https://user-images.githubusercontent.com/1904901/138113943-3cc8949f-1d5c-48c5-b66c-568b9fd390ec.png) Then open Resharper's extension manager and you should be able to install it.

Thank you very much 👍

**Comment by DimitarCC** [comment]
Probably if there are breaking changes to the SDK.

**Comment by rizi** [comment]
> Probably if there are breaking changes to the SDK.

@DimitarCC today R# 2021.3 RTM is released, Enhanced Tooltip seems to work fine, do we still need to upgrade to the latest sdk?
br

**Comment by DimitarCC** [comment]
Its good to be updated to latest version. I already did this and @MrJul merged it. So i guess soon we will have an official version.

**Comment by MrJul** [comment]
Thanks a lot @DimitarCC for the PR, going to test a bit and publish the package. Do you want to be the project maintainer?

To be fair, I'm using Rider 99,9% of the time and haven't launched VS in months, so I'm not using the plugin at all and have lost some interest.

**Comment by DimitarCC** [comment]
@MrJul Yes! It will be great if i can maintain this. I use it all the time so I'd like to be regularly updated and i will be glad to do this.

**Comment by MrJul** [comment]
v3.17.0 for ReSharper 2021.3.0 RTM is released (it's pushed to the plugins gallery - currently pending approval)!
