### ISSUE TITLE
`StackOverflowException` Reported in  `GammaJul.ReSharper.EnhancedTooltip.dll`

### ISSUE THREAD

**Issue by Mike-E-angelo** [MrJul/ReSharper.EnhancedTooltip#168]
Hello,

I recently reported a crash in Visual Studio, and part of that process was to report it to JetBrains here:
https://youtrack.jetbrains.com/issue/RSRP-488164

They are reporting a StackOverflowException in `GammaJul.ReSharper.EnhancedTooltip.dll`.  So I wanted to report that here for your awareness and to establish the next steps towards diagnosis if any.

Thank you for any attention you can provide to this matter.

**Comment by pinkfloydx33** [comment]
After upgrading to the latest version of the extension a few days ago, my VS would consistently crash and close outright. I never saw any errors/exceptions to be able to report, but once I removed the extension it stopped occurring. I am guessing it's probably related to the above, but with nothing showing up in the R# exception window it's hard to say. Is there any other place I might look for logs that could confirm it's the same issue?

**Comment by Mike-E-angelo** [comment]
@pinkfloydx33 you can view mini-DMP's created when a crash occurs in `%LOCALAPPDATA%\CrashDumps` in your Windows Explorer.  If you know your way around a DMP file you can maybe find more information around it.  I have hesitated/resisted such notions as I am more comfortable being a "managed" developer. 😁

**Comment by Mike-E-angelo** [comment]
Ah, apologies @DimitarCC I was operating with the assumption that this is owned by JB/R# team and everyone had access to the DMP file reported in the youtrack issue above.  For further context on my side, the ticket above it is assigned to its own subsystem of `EnhancedTooltip` so that also made me believe that this is R#/JB.

That stated, if you need access to the DMP file I can get it to you.  Please let me know how to proceed.  If there are no security considerations, I can post it to this issue as an attachment, but I am not entirely confident that this is the case.  Again, see: managed developer. 😇

**Comment by DimitarCC** [comment]
Well, since i can not see the attachments in youtrack the only option is to upload it here or send it to me directly on the mail. However it is not good to post personal email in here so i am not sure how to give it to you. So i guess the only option is to have the dump file attached to this thread. I hope it is not large.

**Comment by Mike-E-angelo** [comment]
Looks like DMP files are fine to share, @DimitarCC:
https://superuser.com/questions/659611/is-it-safe-to-publicly-share-minidump-files

I will see if I get mine attached here for you (it's on another machine).

**Comment by Mike-E-angelo** [comment]
[devenv.exe.12280.zip](https://github.com/MrJul/ReSharper.EnhancedTooltip/files/8207179/devenv.exe.12280.zip)
🤞

If you are able to, @DimitarCC please delete from this thread when you do download it, out of an overabundance of caution. :)

**Comment by MrJul** [comment]
Chiming in to help, here's the top of call stack from the dump:

```
Current frame: (MethodDesc 00007ffccdb893d8 +0x20 GammaJul.ReSharper.EnhancedTooltip.VisualStudio.XmlDocRichTextPresenterEx.WrapInNewLine(System.Action`1<System.Xml.XmlElement>, System.Xml.XmlElement))
Child-SP         RetAddr          Caller, Callee
00000081be609070 00007ffd089e8f26 clr!JIT_VirtualFunctionPointer+0x76, calling clr!JitGenericHandleCacheTraits::CompareKeys
00000081be6090c0 00007ffcb0325cc0 00007ffcb0325cc0, calling clr!JIT_WriteBarrier
00000081be609110 00007ffcb0325d8d (MethodDesc 00007ffccdb893d8 +0x7d GammaJul.ReSharper.EnhancedTooltip.VisualStudio.XmlDocRichTextPresenterEx.WrapInNewLine(System.Action`1<System.Xml.XmlElement>, System.Xml.XmlElement))
00000081be609280 00007ffcb0325d8d (MethodDesc 00007ffccdb893d8 +0x7d GammaJul.ReSharper.EnhancedTooltip.VisualStudio.XmlDocRichTextPresenterEx.WrapInNewLine(System.Action`1<System.Xml.XmlElement>, System.Xml.XmlElement))
00000081be6093f0 00007ffcb0325d8d (MethodDesc 00007ffccdb893d8 +0x7d GammaJul.ReSharper.EnhancedTooltip.VisualStudio.XmlDocRichTextPresenterEx.WrapInNewLine(System.Action`1<System.Xml.XmlElement>, System.Xml.XmlElement))
00000081be609560 00007ffcb0325d8d (MethodDesc 00007ffccdb893d8 +0x7d GammaJul.ReSharper.EnhancedTooltip.VisualStudio.XmlDocRichTextPresenterEx.WrapInNewLine(System.Action`1<System.Xml.XmlElement>, System.Xml.XmlElement))
00000081be6096d0 00007ffcb0325d8d (MethodDesc 00007ffccdb893d8 +0x7d GammaJul.ReSharper.EnhancedTooltip.VisualStudio.XmlDocRichTextPresenterEx.WrapInNewLine(System.Action`1<System.Xml.XmlElement>, System.Xml.XmlElement))
00000081be609840 00007ffcb0325d8d (MethodDesc 00007ffccdb893d8 +0x7d GammaJul.ReSharper.EnhancedTooltip.VisualStudio.XmlDocRichTextPresenterEx.WrapInNewLine(System.Action`1<System.Xml.XmlElement>, System.Xml.XmlElement))
00000081be6099b0 00007ffcb0325d8d (MethodDesc 00007ffccdb893d8 +0x7d GammaJul.ReSharper.EnhancedTooltip.VisualStudio.XmlDocRichTextPresenterEx.WrapInNewLine(System.Action`1<System.Xml.XmlElement>, System.Xml.XmlElement))
00000081be609b20 00007ffcb0325d8d (MethodDesc 00007ffccdb893d8 +0x7d GammaJul.ReSharper.EnhancedTooltip.VisualStudio.XmlDocRichTextPresenterEx.WrapInNewLine(System.Action`1<System.Xml.XmlElement>, System.Xml.XmlElement))
00000081be609c90 00007ffcb0325d8d (MethodDesc 00007ffccdb893d8 +0x7d GammaJul.ReSharper.EnhancedTooltip.VisualStudio.XmlDocRichTextPresenterEx.WrapInNewLine(System.Action`1<System.Xml.XmlElement>, System.Xml.XmlElement))
00000081be609e00 00007ffcb0325d8d (MethodDesc 00007ffccdb893d8 +0x7d GammaJul.ReSharper.EnhancedTooltip.VisualStudio.XmlDocRichTextPresenterEx.WrapInNewLine(System.Action`1<System.Xml.XmlElement>, System.Xml.XmlElement))
00000081be609f70 00007ffcb0325d8d (MethodDesc 00007ffccdb893d8 +0x7d GammaJul.ReSharper.EnhancedTooltip.VisualStudio.XmlDocRichTextPresenterEx.WrapInNewLine(System.Action`1<System.Xml.XmlElement>, System.Xml.XmlElement))
00000081be60a0e0 00007ffcb0325d8d (MethodDesc 00007ffccdb893d8 +0x7d GammaJul.ReSharper.EnhancedTooltip.VisualStudio.XmlDocRichTextPresenterEx.WrapInNewLine(System.Action`1<System.Xml.XmlElement>, System.Xml.XmlElement))
00000081be60a250 00007ffcb0325d8d (MethodDesc 00007ffccdb893d8 +0x7d GammaJul.ReSharper.EnhancedTooltip.VisualStudio.XmlDocRichTextPresenterEx.WrapInNewLine(System.Action`1<System.Xml.XmlElement>, System.Xml.XmlElement))
00000081be60a3c0 00007ffcb0325d8d (MethodDesc 00007ffccdb893d8 +0x7d GammaJul.ReSharper.EnhancedTooltip.VisualStudio.XmlDocRichTextPresenterEx.WrapInNewLine(System.Action`1<System.Xml.XmlElement>, System.Xml.XmlElement))
[...repeated many times...]
```

The following calls appears to be infinitely recursive, the base should probably be called instead:
https://github.com/MrJul/ReSharper.EnhancedTooltip/blob/a08e88a8bbb19c59e09e7be27aa2438bfb2e30c3/source/GammaJul.ReSharper.EnhancedTooltip/VisualStudio/XmlDocRichTextPresenterEx.cs#L139:144

**Comment by DimitarCC** [comment]
Indeed, that is the issue...its quite interesting why it didnt happen on my side so far. I Will investigate that and try to fix.

**Comment by DimitarCC** [comment]
OK. I have a new package....Do someone that have the issue willing to test this before to upload it to Jetbrains?
If so here is the prerelease debug package
[JLebosquain.EnhancedTooltip.3.17.6.6-pre.zip](https://github.com/MrJul/ReSharper.EnhancedTooltip/files/8208624/JLebosquain.EnhancedTooltip.3.17.6.6-pre.zip)

**Comment by Mike-E-angelo** [comment]
Awesome thank you all for looking into this and so quickly!  For additional context @DimitarCC this issue is not reproducible and "just happens"... that is, I do not have a scenario I can test for you, so from my perspective you can add it to JetBrains and I will gladly download it when it is available (and report back here if anything further occurs). 👍

**Comment by DimitarCC** [comment]
OK i will upload it to Jetbrains now. Thanks to @MrJul for the help and to all involved.
