### ISSUE TITLE
2022.1 EAP Support

### ISSUE THREAD

**Issue by Mike-E-angelo** [MrJul/ReSharper.EnhancedTooltip#169]
FWIW I attempted to install this extension for [the 2022.1 EAP](https://www.jetbrains.com/resharper/nextversion/#section=windows) which I was recently [forced to install due to this issue](https://youtrack.jetbrains.com/issue/RSRP-488220).  It appears there were errors involved.  I see EnhancedTooltip within those errors so reporting here for your review.

```
Install completed with 5 errors.
  10:18:37.121 ReSharperPlatformVs17_0a286d4b: Error resolving type JetBrains.Platform.VisualStudio.SinceVs11.Shell.Zones.ISinceVs11EnvZone from assembly “JetBrains.Platform.VisualStudio.SinceVs11, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”, request originating from assembly “JetBrains.Platform.VisualStudio.SinceVs11, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”. Could not find the type by its FQN. Is assembly qualification specified? True! Is it of our own assembly? True! Is looking into referenced assemblies allowed? False! Was the qualified referenced assembly encountered during lookup? False! Tried loading an implicitly-referenced assembly? False! Were following a forwarder exported type's assembly ref? No!
  10:18:37.213 ReSharperPlatformVs17_0a286d4b: Error resolving type JetBrains.Lifetimes.Lifetime from assembly “JetBrains.Platform.RdCore, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”, request originating from assembly “GammaJul.ReSharper.EnhancedTooltip, Version=3.9.0.0, Culture=neutral, PublicKeyToken=null”. Could not find a referenced assembly by the TT_ASSEMBLYREF token.
  10:18:37.215 ReSharperPlatformVs17_0a286d4b: Error resolving type JetBrains.Lifetimes.Lifetime from assembly “JetBrains.Platform.RdCore, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”, request originating from assembly “GammaJul.ReSharper.EnhancedTooltip, Version=3.9.0.0, Culture=neutral, PublicKeyToken=null”. Could not find a referenced assembly by the TT_ASSEMBLYREF token.
  10:18:37.218 ReSharperPlatformVs17_0a286d4b: Error resolving type JetBrains.VsIntegration.Shell.IVsEnvironmentInformation from assembly “JetBrains.Platform.VisualStudio.Core, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”, request originating from assembly “JetBrains.Platform.VisualStudio.Core, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”. Could not find the type by its FQN. Is assembly qualification specified? True! Is it of our own assembly? True! Is looking into referenced assemblies allowed? False! Was the qualified referenced assembly encountered during lookup? False! Tried loading an implicitly-referenced assembly? False! Were following a forwarder exported type's assembly ref? No!
  10:18:37.229 ReSharperPlatformVs17_0a286d4b: Error resolving type JetBrains.Lifetimes.Lifetime from assembly “JetBrains.Platform.RdCore, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”, request originating from assembly “GammaJul.ReSharper.EnhancedTooltip, Version=3.9.0.0, Culture=neutral, PublicKeyToken=null”. Could not find a referenced assembly by the TT_ASSEMBLYREF token.

```

**Comment by MrJul** [comment]
3.9 is a 3 years old version: I've just unlisted it from the marketplace since it had a wrong ReSharper version specified (it was incorrectly appearing as compatible with any new EAP).

I'm leaving this issue open for the proper support of R# 2022.1.

**Comment by DimitarCC** [comment]
So i have version that works on 2022.1-eap7. The question now is should i upload it to the JetBrains marketplace as prerelease version or to wait for final release  of 2022.1?
by the way i have issues running R# 2022.1.0-eap7 on VS2022 17.1.2 it gives some exceptions on startup. ;)

**Comment by Mike-E-angelo** [comment]
FWIW @DimitarCC I never check prelease although I probably should.  That is technically the case here.

And I am not surprised about the errors.  I am still having problems getting R# to load in 17.2.0 Preview 2.1 😭

**Comment by DimitarCC** [comment]
Errors in R# are known....There is statement that in next eap release it will be fixed.
So you think is better to wait to general availability reelease and then to release a normal version of the plugin?

**Comment by Mike-E-angelo** [comment]
Ah if it's EAP and it only gets picked up by those with the EAP install I would not mark it as prerelease.  Although marking it as prerelease is technically correct, the only way to acquire it at the moment is via prerelease software (by having the EAP installed), so IMO you're ok with releasing it with RTM mode, because RTM will not see it, if I understand correctly.

That is, if you release it as RTM for the EAP, since it cannot be installed on 2021.x, it will not list for 2021.x (the "real" RTM), and only be listed for EAP.

If I understand that all correctly, then feel free to release it to RTM.  Or at least, that's my vote. :)

**Comment by DimitarCC** [comment]
Well it will be a confusing i think so in this case i think will be better to wait for RTM. Meanwhile for everyone want to install here is the prerelease package
[JLebosquain.EnhancedTooltip.3.17.8-pre.zip](https://github.com/MrJul/ReSharper.EnhancedTooltip/files/8348322/JLebosquain.EnhancedTooltip.3.17.8-pre.zip)

**Comment by Mike-E-angelo** [comment]
Ah at the very least I would make it available on JetBrains as pre-release as they do have some sort of validation/checking for zips and whatnot. :)

**Comment by DimitarCC** [comment]
Added it as prerelease version to JB Marketplace. Pending approval

**Comment by rizi** [comment]
> Added it as prerelease version to JB Marketplace. Pending approval

Yesterday the RTM Version has been released, should I open a new issue for that?

Br

**Comment by DimitarCC** [comment]
The final version is already in marketplace :)

**Comment by rizi** [comment]
> The final version is already in marketplace :)

Thank you very much 👍
