### ISSUE TITLE
Are some standard primitive types still using the default tooltip?

### ISSUE THREAD

**Issue by dsaf** [MrJul/ReSharper.EnhancedTooltip#17]
To reproduce:

1) hover mouse over a 'string' or an 'object' parameter type in a method signature declaration;
2) observe a standard black and white tooltip without any font decorations or icons;

3) hover mouse over a 'Guid' parameter type in a method signature declaration;
4) observe a custom colorful tooltip with an icon and different font colors and decorations.

**Comment by MrJul** [comment]
The first one is from Visual Studio, the second one is from ReSharper (because Color Identifiers is probably checked in R#'s options). Currently Enhanced Tooltip only override ReSharper's tooltips.

Maybe it should also replace VS ones (as an option)? I don't like this inconsistency either.

**Comment by dsaf** [comment]
I guess it could be a nice-to-have customizable option.
