### ISSUE TITLE
Bug: "out" parameters shown as "ref"

### ISSUE THREAD

**Issue by RichardD2** [MrJul/ReSharper.EnhancedTooltip#172]
I have EnhancedToolTip v3.18.0 installed in R# 2022.2.1 / VS2022 v17.3.1.

The tooltip for methods with `out` parameters incorrectly displays them as `ref` parameters:

![image](https://user-images.githubusercontent.com/2158265/185405241-ee93a827-67d1-4924-92f8-74d1f4827672.png)

An example method signature:

```csharp
public static bool TryParse(ReadOnlySpan<char> buffer, out long value, out int charsConsumed, char standardFormat = default)
```

It doesn't matter whether the method is defined in the same project or a referenced package.

**Comment by DimitarCC** [comment]
fixed at MrJul@22ab28a74592cf85f79353ffdb0347c0527f3ac5
pending approval from JetBrains
