### ISSUE TITLE
Maintaining extension on hold!!!

### ISSUE THREAD

**Issue by DimitarCC** [MrJul/ReSharper.EnhancedTooltip#178]
Hello,
I have to share sad news that i will have to stop maintaining this extension at least for now.
This is because my license for Resharper is at the end and JetBrains doesn't want to renew my opensource license because my opensource project has no regular commits in past 3 months.
So i am forced to uninstall resharper which will put on hold maintaining of this extension from my side. :(

I wish it was not like that but unfortunately i have no choice at the moment.

If someone wants to take it over meanwhile feel free to contact @MrJul .

**Comment by DimitarCC** [comment]
@rizi
I can develop it and update it but can not test it without resharper ;)
And the license is about 200 europe for a year. Its quite expencive in my opinion.

**Comment by rizi** [comment]
> @rizi I can develop it and update it but can not test it without resharper ;) And the license is about 200 euros for a year. Its quite expencive in my opinion.

@DimitarCC 
I would be happy to test it for you and I would also donate 20€ if it helps.

R# will cost 166€ in the first year (incl. Vat), so if we find ~8 People we could get you a license.
In the second year it costs 133€.

Details: https://www.jetbrains.com/resharper/buy/#personal

Br

**Comment by DimitarCC** [comment]
@rizi
Well finding sponsors is not easy task...
Espetialy for an opensource project. 
But i am glad there are people like you that willing to help.
We may try with blind coding from my side and you test it out. But that will probably work for SDK updates. If a bug have to be fixed it will be quite dificult without possibility to debug myself.
However since there is no other choice at the moment that is the only options. So we have to at least try out.

I generally already went to free solutions that are almost as good as R#. Well that free solutions doesnt have all the options of R# but they have most of them...

Anyway i dont feel it right to abandon the community that used R# and enhanced tooltip so i will try all possible solution as long as they works.

**Comment by DimitarCC** [comment]
@citizenmatt Thank you!
That means i can close that issue ;)
