### ISSUE TITLE
Actively prompt user to enable Color Identifiers after extension installation

### ISSUE THREAD

**Issue by dsaf** [MrJul/ReSharper.EnhancedTooltip#18]
I have always been installing most popular ReSharper extensions but have never seen the EnhancedTooltip in action because that option is disabled by default. And I am not lazy!

The only reason I have read the homepage is because I wanted to know what is the difference between Roslyn and ReSharper plugins and was looking for some samples :).

It would be nice to show a message box telling how to turn on and explaining the implications.

PS: I have no idea why JetBrains is not turning it on by default and why they are not bundling the EnhancedTooltip by default.

**Comment by MrJul** [comment]
I believe ReSharper's doesn't enable "color identifiers" because it can be quite disrupting since it changes most colors. The tooltip can be considered a side-effect that comes with the highlightings.

That said, I'm considering enabling tooltips for everything (as long as Enhanced Tooltip is enabled in the options), regardless of whether color identifiers is enabled. Similar to #17.

**Comment by dsaf** [comment]
Makes sense, thanks.

**Comment by MrJul** [comment]
In v2.2 identifiers will have pretty tooltips even if color identifiers is disabled, as long as "enhanced identifier tooltips" is checked. Also applies to VS elements you reported in #17.

**Comment by MrJul** [comment]
@dsaf  v2.2 finally released with some of your requests implemented.

**Comment by dsaf** [comment]
@MrJul Just installed it and all the changes look great, thank you! I will keep an eye on stability in 2012; will try it in 2013 as well.

Noticed one edge case thing: when hovering over *var* keywords in the following sample:

```csharp
public async void Test()
{
    var resultTask = Task.Run(() => Enumerable.Empty<string>());

    var results = await Task.WhenAll(resultTask); // This 'var' shows a standard tooltip.
}
```

First *var* - enhanced:

![image](https://cloud.githubusercontent.com/assets/3845650/6896675/cbb61b92-d6e5-11e4-8d08-ebcf7adbccb9.png)

Second *var* - looks standard:

![image](https://cloud.githubusercontent.com/assets/3845650/6896686/edcc5b4c-d6e5-11e4-95e3-4ac315d3f33f.png)

**Comment by dsaf** [comment]
@MrJul it already overtook two items in the ReSharper Gallery - well done :).
