### ISSUE TITLE
Unable to open "GitHub Examples and Documentation" links

### ISSUE THREAD

**Issue by visksm** [MrJul/ReSharper.EnhancedTooltip#180]
In Visual Studio 17.6, there is a new feature which shows API usage examples. This can be opened by clicking the "Github Examples and Documentation" link in the tooltip.
With EnhancedTooltip, this link is displayed in a second tooltip that is separated from the normal tooltip. When trying to open the link, the tooltip closes when moving the mouse over the area separating the two tooltips.

![Snag_654971](https://github.com/MrJul/ReSharper.EnhancedTooltip/assets/56668301/bd7b7e18-ff64-4c8c-94ee-14754b2f7db4)

Video:
https://github.com/MrJul/ReSharper.EnhancedTooltip/assets/56668301/9391b96b-3201-47c4-9cd3-f0a325e50bf6

Would it be possible to move the link to the first tooltip, so it can be opened?

**Comment by IneedHelp** [comment]
This is similar to https://github.com/MrJul/ReSharper.EnhancedTooltip/issues/179

The better solution that fixes the issue with other extensions as well is to get rid entirely of the separate boxes and use a single box with visual separators instead. Hopefully @DimitarCC can help us with this, as he hinted he might do here https://github.com/MrJul/ReSharper.EnhancedTooltip/issues/179#issuecomment-1546903093

**Comment by DimitarCC** [comment]
Yes i will try to redesign the tooltips and will see what will happen. Just that will take some time till i got a bit free time to experiment with this ;)

**Comment by DimitarCC** [comment]
With version 3.21.0 you can click over links without to close the tooltip

**Comment by IneedHelp** [comment]
@DimitarCC thank you for this improvement!
