### ISSUE TITLE
Please add support for R# 2024.1

### ISSUE THREAD

**Issue by rizi** [MrJul/ReSharper.EnhancedTooltip#188]
Hi, R# 2024.1 is just around the corner (RC is already released), could you please add support for it.

Thx in advance!

Br

**Comment by piersmyers** [comment]
The SDK was released yesterday: https://www.nuget.org/packages/JetBrains.ReSharper.SDK

**Comment by DimitarCC** [comment]
Support added. Plugin is available through the extensions in Resharper now.
