### ISSUE TITLE
Show the number of method overloads to match the standard tooltip?

### ISSUE THREAD

**Issue by dsaf** [MrJul/ReSharper.EnhancedTooltip#19]
ReSharper 8.2 / Visual Studio 2013 is displaying the number of method overloads in the form of:

"... (+ 1 overload(s))"

The ET does not currently display this.

**Comment by MrJul** [comment]
Good catch.

It's Visual Studio: ReSharper doesn't display it at all (you can turn off Enhanced Tooltip in ReSharper > Options > Environment > IntelliSense > Enhanced Tooltip > Enhanced identifier tooltips).

Could be a nice option to have.

**Comment by dsaf** [comment]
Thank you very much for such a quick response to every request!
Would you be open to more suggestions? I feel kind of embarrassed because opening issues/ideas is so much simpler than actually implementing them.
To be more specific it relates to presentation of applied custom attributes - there is definitely some useful information to show that neither VS nor R# are showing.

**Comment by MrJul** [comment]
Go on, suggest! I can't promise I'll implement everything, but ideas are always welcome.
