### ISSUE TITLE
Compatibility with v2024.1.2

### ISSUE THREAD

**Issue by IneedHelp** [MrJul/ReSharper.EnhancedTooltip#190]
Hello, is there any estimate for when the plugin will be compatible with
    Version: 2024.1.2    Build: 2024.1.2.65536  from 7 May 2024 ?

**Comment by DimitarCC** [comment]
Hi. What's the problem? Doesn't install? Or doesn't work correct? I am with 2024.1.2 and it works there. But ofcource on my side i have upgraded from previous version.

**Comment by IneedHelp** [comment]
Sorry for the late reply, I just got a chance to check again now, it must've been an installation issue or something, because I couldn't install other extensions either, but now it works fine. Sorry for opening this non existing issue.
