### ISSUE TITLE
Tooltip in C++ code does not apear at all after install the extension

### ISSUE THREAD

**Issue by plenartowicz** [MrJul/ReSharper.EnhancedTooltip#191]
Hi,
I think the EnhancedTooltip has a negative impact of ReSharper C++. After I installed the extension the tooltips in C++ code do not appear at all. 

Suspending the ReSharper or uninstalling the extension bring them back. 

So, I think there is a bug or I don't know how to use the extension to resolve the issue.

I'm pretty sure that the issue has appeared since Resharper 2023.x was released.

Just to be clear, it's about this kind of tooltip:
![image](https://github.com/MrJul/ReSharper.EnhancedTooltip/assets/34403053/ef7f9e1a-d26e-44bb-91f5-1ed50608c97e)

**Comment by DimitarCC** [comment]
Hmmm that is interesting.....
I have to investigate that but difficult since i don't use c++ in VS

**Comment by plenartowicz** [comment]
I'm not sure it could help but there is the same issue when it is installed ReSharper for C# only (without C++ version). 
So maybe the extension has missing "if (I am in C# source code) then use EnhancedTooltip else use Visual Studio tooltip" ?

I'm just guessing

**Comment by DimitarCC** [comment]
Fixed in 7a38275c8eaff32ad598c35e4b7f35c1e7fdc509
