### ISSUE TITLE
Please add support for R# 2024.3

### ISSUE THREAD

**Issue by rizi** [MrJul/ReSharper.EnhancedTooltip#194]
Hi, it would be great if you could add support for R# 2024.3, the RC was released yesterday.

If you already have a version, could you please provide a download link?

br

**Comment by DimitarCC** [comment]
So i have a version but it will be officially released when there is official release of 2024.3.0.
Till then use this

[JLebosquain.EnhancedTooltip.3.27.0-pre.nupkg.zip](https://github.com/user-attachments/files/17692079/JLebosquain.EnhancedTooltip.3.27.0-pre.nupkg.zip)

**Comment by rizi** [comment]
> So i have a version but it will be officially released when there is official release of 2024.3.0. Till then use this
> 
> [JLebosquain.EnhancedTooltip.3.27.0-pre.nupkg.zip](https://github.com/user-attachments/files/17692079/JLebosquain.EnhancedTooltip.3.27.0-pre.nupkg.zip)

Thx, the nupkg.zip is absolutely fine!

Br

**Comment by DimitarCC** [comment]
Yes the plugin is available now in their marketplace
