### ISSUE TITLE
Only XML </ summary> documentation is displayed at the moment

### ISSUE THREAD

**Issue by dsaf** [MrJul/ReSharper.EnhancedTooltip#20]
E.g. users have to use keyboard to see the complete method parameter information (Ctrl+Shift+Space in VS layout).
Some tags are probably not viewable without navigating to source or online documentation.
It would be great to display all the XML documentation everywhere (based on configuration).

**Comment by MrJul** [comment]
Personally, I use Quick Documentation for that (Ctrl+Q in IDEA layout or Ctrl+Shift+F1 in VS layout).

Directly in the tooltip? That could get quite verbose, but why not, as an option (probably disabled by default), if you like your tooltips huge :)

**Comment by dsaf** [comment]
I would love huge tooltips, but making them configurable is definitely a good idea!

I was not aware of Quick Documentation. It feels kind of alien to the rest of ReSharper experience.

PS: ET is crashing intermittently on my machine (no particular pattern - had to restart the Visual Studio), are there any ReSharper / extension logs for me to check?

**Comment by MrJul** [comment]
Crashing as in, no more colors? Are you on R# 8.2 or 9.0 ? You can run VS with the /ReSharper.Internal command line switch and see if some exceptions are thrown.

**Comment by dsaf** [comment]
Yes, no more colors, R# 8.2.3000.5176, Visual Studio 12.0.31101.0 Update 4.

I will try that switch for a while tomorrow.

**Comment by MrJul** [comment]
I saw that in R# 8.2 too, I'm not sure how to reproduce. Didn't see it at all on 9.0 yet. Will appreciate any info.

**Comment by dsaf** [comment]
Tried the /R...Internal flag but there were no exceptions thrown when ET turned off.
Now trying the VS /log flag.

**Comment by MrJul** [comment]
Opened #27 for this bug, please post your results there.

**Comment by DimitarCC** [comment]
This is too old and i dont think the original request is good to be done directly in tooltip. So close this.
