### ISSUE TITLE
When hovering over an argument in method invocation only the nature of the argument is shown not it's role in method invocation

### ISSUE THREAD

**Issue by dsaf** [MrJul/ReSharper.EnhancedTooltip#21]
For example consider this method invocation:

```csharp
var dude = "erlich.bachman@aviato.com";
var message = "Pied Piper will be at TechCrunch Disrupt";

messageService.Send(dude, message);
```

When hovering over 'dude' and 'message' arguments in method invocation it would be great to show not only that they are local variables (their "nature"), but also the corresponding </ param> XML documentation if available (thier "contextual role").

**Comment by MrJul** [comment]
This could be useful in simple calls.

In more complex cases, it could be confusing.
Consider having the mouse on `ToString` in the following code:
```
Int32.Parse(ToString())
```

There will be documentation for `ToString`, and for the first param of `Int32.Parse`.
What do you think?

**Comment by dsaf** [comment]
Fair point... Could they be combined to show both "roles"? :

"
(method) [NotNull] string System.Object.ToString()
Returns a string that represents the current object.
-----------------------------------------------------
(argument) s: A string containing a number to convert.
"

**Comment by dsaf** [comment]
Copied from #45 duplicate:

--
Let's say we have some code that looks like this:

```csharp
[DefaultValueSizef(100, 100)]
public SizeF Size { get; set; }
```

Currently ET will show the type info *```struct System.Int32```* when hovering over ```100```. It would be helpful to (additionally) show that it's an argument *```float width```*.

This is more of a suggestion rather than a request.

PS: I do use the *Display constructor references for attributes as: Constructor and type* option - thank you :).
