### ISSUE TITLE
Applied custom attributes are shown as constructors - not types

### ISSUE THREAD

**Issue by dsaf** [MrJul/ReSharper.EnhancedTooltip#23]
This not just extension's but ReSharper's ommission.

Hover over an applied documented attribute e.g. '[AttributeUsage(...)]':

1) ReSharper turned off: '(class) ...' tooltip is displayed along with the </ summary> XML doc.
2) ReSharper turned on: '(constructor) ...' tooltip is displayed.

I would say both constructor and class info should be displayed, with latter being more useful.

**Comment by dsaf** [comment]
This could/should be improved further:

https://github.com/MrJul/ReSharper.EnhancedTooltip/issues/24

https://github.com/MrJul/ReSharper.EnhancedTooltip/issues/25

**Comment by MrJul** [comment]
Ah, I've been using ReSharper for so long that I forgot the original VS behavior, which is definitely better. Let's make it configurable (again!): ctor, type or ctor+type.
