### ISSUE TITLE
Show the first inherited type and all inherited interfaces

### ISSUE THREAD

**Issue by dsaf** [MrJul/ReSharper.EnhancedTooltip#24]
Consider the WPF class hierarchy: http://4.bp.blogspot.com/-FSsPICI9wb0/TgIqtcQg34I/AAAAAAAAAEo/DBLnAe1CcvQ/s1600/WPF+Class+Hierarchy.PNG

It would be great to know that Line is a Shape, Grid is a Panel and Visual is a DependencyObject - on a simple mouse hover, without having to navigate to definitions.

Bonus suggestion: show how many other classes are there on same inheritance level? This would "feel consistent" with showing the number of method overloads for methods: "... (+ 1 implementation(s))"

**Comment by MrJul** [comment]
I use Quick Documentation or Inspect Hierarchy for this. Aren't all interfaces a bit too much information? Genuine question, I'm interested in your usages.

**Comment by dsaf** [comment]
Maybe it's just my taste, but when reading code, ideally I would like NOT to have to open a different window / file unless I am interested in global usages / implementation details. For me interfaces, attributes, signatures, 'annotation contracts' altogether constitute a contract: http://en.wikipedia.org/wiki/Design_by_contract

Basically if you had a combobox with presets:
"- minimal (just the colouring);
- balanced (recommended extra bits of information);
- AOP (balanced + custom attribute details);
- full (always display all available information everywhere)"

I would start with "full" and then I would turn off things I don't like (if any!).
