### ISSUE TITLE
Custom attributes are not treated as a first-class concept

### ISSUE THREAD

**Issue by dsaf** [MrJul/ReSharper.EnhancedTooltip#25]
Custom attributes are a very special (underappreciated) language construct. The fact that they are classes is merely an implementation detail.

They can be:
- selectively applied to specific language elements;
- allowed (or not) to be applied multiple times;
- inherited;
- overriden.

```csharp
[System.AttributeUsage(AttributeTargets.Class | AttributeTargets.Method, AllowMultiple = false, Inherited = true)]
```

Action items:

1) create a separate kind of tooltip for attributes: "(attribute) ..."
2) present fundamental attribute information in a nice way:
	- target(s);
	- multiplicity;
	- inheritability;
	- whether it overrides an inherited attribute.
3) improve the e.g. "(class) ..." tooltip to show:
    - inherited attributes;
	- iherited but overriden attributes (ideally the difference, but it could be hard);

Code contracts are often implemented using custom attributes but can be reated as a first-class concept as well [link issue #7].

**Comment by dsaf** [comment]
Code contracts are often implemented using custom attributes but can be reated as a first-class concept as well: https://github.com/MrJul/ReSharper.EnhancedTooltip/issues/26

**Comment by MrJul** [comment]
To clarify:

Targets, multiplicity, inheritability are properties of the attribute class itself.
However, whether it overrides an inherited attribute is a property of the attribute instance (or, to be more precise, of the member onto which it's applied). 

This issue will track 1) and 2), except the override part. I'm opening another issue for inherited/overridden attribute instances.

**Comment by dsaf** [comment]
Makes sense.

**Comment by MrJul** [comment]
Preview (all options enabled):
![attribute](https://cloud.githubusercontent.com/assets/1623034/9977393/7941c858-5f06-11e5-88c3-846a6e009dd7.png)

**Comment by dsaf** [comment]
Wow!
