### ISSUE TITLE
Standard tooltip is being displayed on 'var' keyword

### ISSUE THREAD

**Issue by dsaf** [MrJul/ReSharper.EnhancedTooltip#28]
(Instead of a colorful ET one)

![image](https://cloud.githubusercontent.com/assets/3845650/6272508/044561a6-b860-11e4-8970-4a74ced8d899.png)

**Comment by dsaf** [comment]
Is it fixed via https://github.com/MrJul/ReSharper.EnhancedTooltip/issues/17 ?

**Comment by MrJul** [comment]
No, it isn't. ReSharper doesn't add any reference under `var`, it seems to have special handling. Shouldn't be too hard to special case this too.
