### ISSUE TITLE
Would you be open to a JetBrains-style logo?

### ISSUE THREAD

**Issue by dsaf** [MrJul/ReSharper.EnhancedTooltip#29]
![image](https://cloud.githubusercontent.com/assets/3845650/6278103/fbf50ebc-b88b-11e4-8687-1377dbd0088f.png)

...not a perfect match (needs to be fatter), but along the lines of:

![image](https://cloud.githubusercontent.com/assets/3845650/6278112/0d080394-b88c-11e4-92df-6c14317df714.png)

Graphical design is very subjective, so not going to defend.

**Comment by MrJul** [comment]
Why not! The current one was made quickly in 5 minutes: I'm not really attached to it.

**Comment by dsaf** [comment]
![image](https://cloud.githubusercontent.com/assets/3845650/6311199/27377ac6-b957-11e4-90b8-b0a5a119a35e.png)

Harder than expected! Generating raster versions is a separate step.

**Comment by dsaf** [comment]
New icons are now done, same resolutions available. Do I need to submit a pull request?

Also check the promo image - to grab attention on Twitter etc.:

![promo](https://cloud.githubusercontent.com/assets/3845650/6320444/76dd1228-bad5-11e4-9907-4f8c3ee3f2c4.png)

**Comment by MrJul** [comment]
Thank you! I would appreciate a pull request with the vector and raster icons.

Regarding the promo image, I'm not a fan of the big "2" (version doesn't matter here), and the screen capture is kinda pixelated. The logo is nice though :)

**Comment by dsaf** [comment]
Cool, I started learning how to use Git today. Hopefully will upload them soon.

Promo image is kind of a play on JetBrains home page hero section at the top :) - hence the version number, but I can remove it. Yeah, screen capture could be improved, true.
