### ISSUE TITLE
Possible bug in UIResources.9.0.tt?

### ISSUE THREAD

**Issue by citizenmatt** [MrJul/ReSharper.EnhancedTooltip#31]
Just browsing the source, and spotted this line, is it a bug? Should it be `UIResources.9.0.xaml`?

https://github.com/MrJul/ReSharper.EnhancedTooltip/blob/master/GammaJul.ReSharper.EnhancedTooltip/Presentation/UIResources.9.0.tt#L6

**Comment by MrJul** [comment]
It's meant this way: `UIResources.9.0.xaml` is generated from `UIResources.8.2.xaml`, since only namespaces have changed. I can change the suffix to `.generated.xaml` to make it obvious.
