### ISSUE TITLE
Use VSSDK packages for Visual Studio references?

### ISSUE THREAD

**Issue by citizenmatt** [MrJul/ReSharper.EnhancedTooltip#32]
Just a suggestion - it might be worth using the [VSSDK nuget packages](https://www.nuget.org/packages?q=VSSDK) for the Visual Studio references. Makes it very easy to reference Visual Studio SDK assemblies, and get the right versions, and so on. They're on [GitHub](https://github.com/tunnelvisionlabs/vsxdeps#readme), too, and Sam's really responsive if there's something missing.

**Comment by MrJul** [comment]
I didn't know about those packages. That's better than using the GAC ones. I will definitely use them, thank you Matt.

**Comment by MrJul** [comment]
Packages used in v2.4
