### ISSUE TITLE
Limit width of tooltip

### ISSUE THREAD

**Issue by citizenmatt** [MrJul/ReSharper.EnhancedTooltip#33]
The tooltip for parameters, methods, etc. will stretch the full width of the screen with a lot of parameters, or with xml doc that isn't formatted nicely. Perhaps limit the width of the tooltip to something like 1/3rd of the screen?

**Comment by MrJul** [comment]
That's a good idea, it could even be configurable. (One third isn't much if the resolution is small.)

For reference: VS's tooltip uses 90% of the screen width, ReSharper's one uses 100%.

**Comment by Funbit** [comment]
+1
Thank you for the plugin, it went to my must have list already, but shorter tooltips will make it perfect!
![long](https://cloud.githubusercontent.com/assets/5512433/6920973/ce93af56-d7fc-11e4-921e-94a184596836.png)

**Comment by MrJul** [comment]
A new option (enabled by default) has been added to limit the width of the tooltip in the upcoming v2.4. By default it's 50% of the screen width.
