### ISSUE TITLE
Improve text rendering

### ISSUE THREAD

**Issue by michael-damatov** [MrJul/ReSharper.EnhancedTooltip#42]
The WPF display text rendering can be improved by setting the `TextOptions.TextFormattingMode` in XAML.

e.g.

    TextOptions.TextFormattingMode="Display"

**Comment by MrJul** [comment]
Indeed, it's on `Ideal` currently. I agree that `Display` looks better on small fonts, but not on larger ones (and it depends on resolution). A configurable setting might be the best solution.
