### ISSUE TITLE
Tooltips not readable with 'Dark with Light Editor' from Color Themes

### ISSUE THREAD

**Issue by luedi** [MrJul/ReSharper.EnhancedTooltip#44]
I prefer to use the above theme from the Color Themes AddIn. The text is not readable as it is dark gray on black background. Is there any way to change the colors used by ET?

![2015-04-24_13h13_37](https://cloud.githubusercontent.com/assets/12098314/7317726/3cf53840-ea84-11e4-83bd-e529639b4424.png)

**Comment by MrJul** [comment]
Good catch. The tooltip background should probably use the text editor's color rather than VS' background color.

**Comment by MrJul** [comment]
Fixed in upcoming v2.4

**Comment by tormozit** [comment]
I have 2.10.1 and VS 2015. I've tried hard to change tooltip background but only was able to change standart tooltip background (Options-Environment-Tooltip)
![2017-02-25_093549](https://cloud.githubusercontent.com/assets/11896251/23328915/e347b742-fb3d-11e6-8852-5cb560ce53b3.png)
Parameter info tooltip stays always the same color
![2017-02-25_093333](https://cloud.githubusercontent.com/assets/11896251/23328895/94dae4e4-fb3d-11e6-89af-4c228d73df32.png)

So I wish
1. Bigger or customizable size of parameter info tooltip border 
2. Parameter info tooltip should use Environment-Tooltip background

**Comment by MrJul** [comment]
@tormozit Currently, the text editor's background is always used for the tooltip, ensuring that colors look the same. I can add an option to use the background color from the settings, I've opened an issue for this (#98). The parameter info is entirely managed by ReSharper though, I'll see what can be done.

**Comment by citizenmatt** [comment]
Does this mean ReSharper is using the wrong background for the tooltip?

**Comment by MrJul** [comment]
No, R# doesn't change VS' tooltip background so it's fine.
ET does to make sure "light with dark editor" and "dark with light editor" themes are readable, at the expense of customization.
