### ISSUE TITLE
Show parameter info when hovering over a literal method argument?

### ISSUE THREAD

**Issue by dsaf** [MrJul/ReSharper.EnhancedTooltip#45]
Let's say we have some code that looks like this:

```csharp
[DefaultValueSizef(100, 100)]
public SizeF Size { get; set; }
```

Currently ET will show the type info *```struct System.Int32```* when hovering over ```100```. It would be helpful to (additionally) show that it's an argument *```float width```*.

This is more of a suggestion rather than a request.

PS: I do use the *Display constructor references for attributes as: Constructor and type* option - thank you :).

**Comment by MrJul** [comment]
Isn't that similar to #21? :)

**Comment by dsaf** [comment]
Yes, actually :), although the samples are different.
