### ISSUE TITLE
Minor feature: show if a class is abstract

### ISSUE THREAD

**Issue by dsaf** [MrJul/ReSharper.EnhancedTooltip#49]
Would it be possible to show if the class is abstract? They are quite special after all. Otherwise I have to navigate to sources or use unrecommended ```*Base``` naming convention.

Maybe simply show them as *```(abstract class)```* instead of *```(class)```*?

Case in point: extensions methods are shown as *```(extension)```* rather than *```(method)```*.

PS: Visual Studio 2015 Release, R# 9.1.2.
PPS: I have just noticed the icon differentiation, but is it enough?

**Comment by MrJul** [comment]
Everything is possible ;) I will add an option to show class modifiers (abstract/sealed/static)

**Comment by dsaf** [comment]
Thank you :).
