### ISSUE TITLE
Double tooltip on VS 2015 + R# 9.1.3

### ISSUE THREAD

**Issue by dsaf** [MrJul/ReSharper.EnhancedTooltip#50]
Not sure if it's a mis-configuration or a bug:

![image](https://cloud.githubusercontent.com/assets/3845650/8984269/6dc8ca8c-36c8-11e5-9cbd-10d192b6c512.png)

**Comment by MrJul** [comment]
I didn't update EnhancedTooltip yet to special case new Roslyn tooltips in VS2015. Should come soon.
Related: #39

**Comment by dsaf** [comment]
Understood, thanks.
