### ISSUE TITLE
VS2015 dark theme

### ISSUE THREAD

**Issue by lniedzielski** [MrJul/ReSharper.EnhancedTooltip#54]
My dev environment:
VS2015 RTM 14.0.23107.0 D14REL
Resharper 9.1.3
Enhanced Tooltip 2.3.1

Characters like <>=. appear black in tooltip pop-ups therefore are barely visible on dark theme in VS2015. I'd expect this signs to be in light colors here:

![tooltip](https://cloud.githubusercontent.com/assets/1392640/9330422/9571fe8c-45b9-11e5-8a8f-961ece707ef3.png)

**Comment by MrJul** [comment]
Should already be fixed in upcoming 2.4 (will be released with ReSharper 9.2 which is currently in RC).

**Comment by MrJul** [comment]
v2.4 is out for ReSharper 9.1. 9.2 following soon. Let me know if this issue is solved for you.

**Comment by lniedzielski** [comment]
Works as expected. Thank you.
