### ISSUE TITLE
Options do not show up in search results

### ISSUE THREAD

**Issue by citizenmatt** [MrJul/ReSharper.EnhancedTooltip#67]
Consider using `SimpleOptionsPage` or `CustomSimpleOptionsPage`, which makes it dead easy to add simple options such as checkboxes, drop downs and text boxes in a vertical stack, and it handles searching for you. It also means you can get rid of all of the xaml, unless you want a custom view model for a specific settings. You can see an example in the [StyleCop settings](https://github.com/StyleCop/StyleCop/blob/master/Project/Src/AddIns/ReSharper/Options/StyleCopOptionsPage.cs), and the [Cyclomatic Complexity plugin](https://github.com/JetBrains/resharper-cyclomatic-complexity/blob/master/src/CyclomaticComplexity/Options/ComplexityAnalysisOptionPage.cs) shows a couple of custom views and view models, such as a hyperlink [view](https://github.com/JetBrains/resharper-cyclomatic-complexity/blob/master/src/CyclomaticComplexity/Options/HyperlinkOptionView.xaml) and [view model](https://github.com/JetBrains/resharper-cyclomatic-complexity/blob/master/src/CyclomaticComplexity/Options/HyperlinkOptionViewModel.cs).

**Comment by MrJul** [comment]
Thanks you, I'll have a look :)

Honestly, I think XAML is pretty good to describe UI. In code, it's quickly a mess. That said, the option page should definitely handle search.
