### ISSUE TITLE
Cuts long lines of code

### ISSUE THREAD

**Issue by dsaf** [MrJul/ReSharper.EnhancedTooltip#69]
![image](https://cloud.githubusercontent.com/assets/3845650/10399272/a237c6c4-6ea9-11e5-9104-8ecd8123ab2d.png)

This is an unreasonably named method, but I have seen such cutting on a "normal" code (fully qualified type names can make any line of code look big).

**Comment by MrJul** [comment]
Duplication of already fixed #55. I might as well release the next version already (I was planning to add more features regarding attributes, but didn't have much time to do so lately).

**Comment by MrJul** [comment]
As a workaround, you can increase the maximum width of the tooltip. Won't work if you get past 100% though :)

**Comment by dsaf** [comment]
Thanks :).
