### ISSUE TITLE
Options to show non-fully qualified names

### ISSUE THREAD

**Issue by dsaf** [MrJul/ReSharper.EnhancedTooltip#72]
There are multiple levels of namespaces in some projects. It means that fully-qualified names are too long to scan quickly in a tooltip. It would be great to have the following combinable configuration options:

1) do not show fully-qualified names at all;
2) do not show fully-qualified names for code coming from System.\* namespaces;
3) do not show fully-qualified names for code interacting within same namespace (common root namespaces can optionally be shown as three dots).

There could be further options to differentiate between solution's and third party libraries' namespaces but I am not sure about the use case.

![image](https://cloud.githubusercontent.com/assets/3845650/10541641/ac391bf8-740a-11e5-9236-9110c526045f.png)

**Comment by MrJul** [comment]
Related: #51
I like your suggestion of handling System and the current namespace specially.

While waiting for this to be implemented, consider using different colors for namespaces and types, it helps a lot.

**Comment by dsaf** [comment]
@MrJul That's a good suggestion - thanks! I am already using a custom color for ```#region```, but namespaces are more common.
