### ISSUE TITLE
[Bug?] Double tooltip in XAML on VS 2015 + R# 9.2

### ISSUE THREAD

**Issue by dsaf** [MrJul/ReSharper.EnhancedTooltip#76]
Not sure if XAML is even supported by ET - it looks like a standard tooltip. Not sure if it's a ReSharper, Roslyn or ET related behavior.

Example:

![image](https://cloud.githubusercontent.com/assets/3845650/10905664/91bc22b8-8213-11e5-9228-6241f5f78881.png)

Another one:

![image](https://cloud.githubusercontent.com/assets/3845650/10905845/f088f536-8214-11e5-8685-fbc760a6a974.png)

**Comment by dsaf** [comment]
Stopped after restarting VS.

**Comment by MrJul** [comment]
I've seen double ReSharper highlightings before, that's not specific to XAML nor to Enhanced Tooltip.

**Comment by MrJul** [comment]
I'll close this as the only double tooltips I've seen are reproducible with ET disabled. Feel free to reopen if needed.
