### ISSUE TITLE
XML documentation from interfaces or base classes is not inherited

### ISSUE THREAD

**Issue by Mertsch** [MrJul/ReSharper.EnhancedTooltip#79]
I have the following code

```
public interface IItemFilter
{
    /// <summary>
    /// Get the whitelist of zone IDs to include.
    /// If <c>null</c> include everything.
    /// </summary>
    [CanBeNull]
    int[] ZoneIds { get; }
}
```

and

```
public sealed class ItemFilter : IItemFilter
{
    [CanBeNull]
    public int[] ZoneIds { get; set; }
}
```

When hovering over `IItemFilter.ZoneIds` I get the description when hovering over `ItemFilter.ZoneIds` I don't :(

Thanks for looking into the issue.

**Comment by MrJul** [comment]
That's not specific to Enhanced Tooltip: the plugin reuses the documentation provided by ReSharper here, and R# doesn't automatically looks for the XML doc on the interface.

That's said, the plugin is supposed to *enhance* the standard tooltip so I can mark this as a feature request :)

**Comment by Mertsch** [comment]
@MrJul Thank you for the info.
One thing that puzzles me though is that when I uninstall this extension and leave R# enabled, I do get inherited XML docs. That is why I suspected it to be an issue with this extension.

**Comment by MrJul** [comment]
@Mertsch That's not what I currently observe, which ReSharper version are you using?

**Comment by Mertsch** [comment]
@MrJul I am using R# 10.0 RTM with Visual Studio 2015 RTM

**Comment by Mertsch** [comment]
@MrJul Ok, now it gets really confusing. It seems to be a timing issue with this extensions.
I just had an inherited tooltip, as you can see here but it only works in very rare cases where the source code window is still loading.
First you see only the signature, then after a few ms the dashed line and the XML doc. If you give it some time to be all ready (VS is no longer busy, R# has applied his colors, ...) then you do *not* get XML doc text.

![rsexttoolbug](https://cloud.githubusercontent.com/assets/9402861/11189413/4300f96e-8c90-11e5-9385-974ea0ce291a.png)

**Comment by MrJul** [comment]
@Mertsch Do you still have this problem with the latest ReSharper version (2016.2.2) and latest VS (2015 updae 3)?

**Comment by Mertsch** [comment]
@MrJul I stopped using R# enhanced tooltips (R# option and this addon, as it did not work reliable enough)
Since I upgraded to 2016.3 EAP 1 I can't try again. Will you update for EAPs or just release versions?

**Comment by MrJul** [comment]
Sorry, I'll only update for release versions.
If you try Enhanced Tooltip again when R# 2016.3 is released, please let me know.

**Comment by Mertsch** [comment]
@MrJul OK, will do so.
Since I am EAP junkie I won't be able to use this extension much anymore anyway :)

But I will try to report the R# Bugs to JetBrains, so that R#'s ToolTips can be used as a reliable base at least.

**Comment by MrJul** [comment]
I'll close this issue since ReSharper now supports `<inheritdoc />` for this exact purpose, which Enhanced Tooltip gets for free.
