### ISSUE TITLE
Tooltip is flickering if it can't find where to place itself

### ISSUE THREAD

**Issue by levdimov** [MrJul/ReSharper.EnhancedTooltip#80]
It can be easily reproduced by writing File.ReadAllLines method at the bottom. If you navigate to ReadAllLines, the tooltip will begin to flicker

(VS 2015, ReSharper 10.0.1, Windows 10)
![image](https://cloud.githubusercontent.com/assets/2759370/11245497/7ae99ce4-8e2c-11e5-8a91-793f16eb885a.png)

**Comment by MrJul** [comment]
Indeed, reproduced!
However, I need to test without Enhanced Tooltip, but I'm not sure there's a correct way to fix this, it's VS that ultimately chooses where to display the tooltip.

**Comment by MrJul** [comment]
I can reproduce the same thing with the standard VS tooltip, on a fresh VS 2015 Update 2 instance, without Enhanced Tooltip nor ReSharper. I'm going to close this as a VS issue.
