### ISSUE TITLE
Show base type/implemented interfaces which are my code only

### ISSUE THREAD

**Issue by hmemcpy** [MrJul/ReSharper.EnhancedTooltip#81]
I love this feature to be able to understand the hierarchy at a glance, but it can be overwhelming at times (e.g. `string`)
![image](https://cloud.githubusercontent.com/assets/601206/11322976/b11fe8e0-910b-11e5-94e1-e6e6f3b29d40.png)

I'd like a mode where the base types/interfaces are only shown for my own code and hidden (or, de-emphasized) for BCL/CLR types.

**Comment by MrJul** [comment]
I completely agree, would be nice to have :)

**Comment by hmemcpy** [comment]
:kiss:

**Comment by dsaf** [comment]
How about a configurable option to aggregate any type of tooltip element into a row? In this case via namespaces:

```
[Implements] System: ICloneable, IComparable, IConvertible...
```
