### ISSUE TITLE
Please improve the display effect for <remark> and <seealso> comment element

### ISSUE THREAD

**Issue by sgjsakura** [MrJul/ReSharper.EnhancedTooltip#82]
I suggest that you can split a new row for `remark` element with "remark" icon, just similar as "inherits" information.

Currently the `seealso` element will listed after the summary text, this may be confusing. Please consider to generate seperate rows for each `seealso` element, or just remove this part.

Thank you very much for your product!

**Comment by MrJul** [comment]
It's a nice suggestion! I will probably implement it, thank you.
