### ISSUE TITLE
Removes docs from the Visual Studio Tools for Unity

### ISSUE THREAD

**Issue by DmitriyYukhanov** [MrJul/ReSharper.EnhancedTooltip#84]
Hey, I have such issue.

When I have R# and latest VSTU (https://visualstudiogallery.msdn.microsoft.com/8d26236e-4a64-4d64-8486-7df95156aba9) installed, I can see docs for the Unity APIs, like this:
![Unity API docs](https://cloud.githubusercontent.com/assets/883587/12277143/ebf08036-b98a-11e5-96d5-673ac5c748a2.png)

But when I install EnhancedTooltip, those docs disappear from tooltips:
![no Unity API docs](https://cloud.githubusercontent.com/assets/883587/12277189/1cc7d326-b98b-11e5-9bac-5fd378f9212f.png)

Would be nice to know if it's possible to workaround this somehow.

**Comment by MrJul** [comment]
I can't seem to reproduce this problem currently with latest versions:
- Visual Studio 2015 Update 2
- VSTU 2.2
- ReSharper 2016.1.1
- Enhanced Tooltip 1.8.0
Can you?

**Comment by DmitriyYukhanov** [comment]
Just tried - everything works fine now, thanks!
