### ISSUE TITLE
Provide an ability to see property accessors in a tooltip on property

### ISSUE THREAD

**Issue by ViIvanov** [MrJul/ReSharper.EnhancedTooltip#86]
MSVS shows an property accessors in tooltips and this is nice.

![image](https://cloud.githubusercontent.com/assets/795200/13143131/cc9c2cbe-d652-11e5-8656-fdcbc83285ce.png)

Please, add an option to show accessors. Arrows on icon on property is good, but not `{ get; set; }` looks better.

**Comment by MrJul** [comment]
I like this :) Will probably implement.
