### ISSUE TITLE
Support inheritdoc-tag

### ISSUE THREAD

**Issue by Gitii** [MrJul/ReSharper.EnhancedTooltip#88]
Hi,

I suggest to add support for `<inheritdoc/>`-tag. Its used by [Sandcastle](https://stackoverflow.com/questions/824007/ways-to-synchronize-interface-and-implementation-comments-in-c-sharp), but its not official. That also addreses (some how) issue #79 .

Thank you very much for your product!

**Comment by MrJul** [comment]
ReSharper 2016.2 now supports `inheritdoc`. Enhanced Tooltip gets it for free :)
