### ISSUE TITLE
Resharper 2016.1 Extension Manager doesn't show this package anymore

### ISSUE THREAD

**Issue by andrewpsy** [MrJul/ReSharper.EnhancedTooltip#89]

**Comment by rob8861** [comment]
Same here. After the upgrade to 2016.1 , the extension was removed and is no longer available in the extension manager.

**Comment by MrJul** [comment]
Enhanced Tooltip is now available for ReSharper 2016.1!

**Comment by andrewpsy** [comment]
That was quick. Thank you.

**Comment by rob8861** [comment]
Thank you.

**Comment by andrewpsy** [comment]
@MrJul 
This just happened again for the 2016.2 update.
Thanks in advance.
