### ISSUE TITLE
Add support for R# 2016.3 EAP 9 (VS 2017 RC)

### ISSUE THREAD

**Issue by stackalloc** [MrJul/ReSharper.EnhancedTooltip#95]
Thank you

**Comment by DimitarCC** [comment]
Yes i agree. I have managed to build the project myself with the new Resharper SDK however i ended up with double tooltips (one is EnhancedTooltip tooltip and another is standart Vs tooltip rendered below the EnhancedTooltip). I dont know what i do wrong.

**Comment by nms-plavoie** [comment]
Any news for the support of VS2017 RC and ReSharper EAP 11/RC ?

**Comment by MrJul** [comment]
Enhanced Tooltip 2.10 is now available for ReSharper 2016.3 RTM.
VS2017RC hasn't been tested though, and won't be officially supported by Enhanced Tooltip until VS 2017 RTM.
