### ISSUE TITLE
Support for R# 2016.3 RTM

### ISSUE THREAD

**Issue by DevHim** [MrJul/ReSharper.EnhancedTooltip#96]
One of my favorite extensions, please update.
Thanks.

**Comment by DimitarCC** [comment]
I will joint to this request. Please update it!!!

**Comment by MrJul** [comment]
Don't worry, I will update it soon, using it daily myself :)

**Comment by DimitarCC** [comment]
Well i tried to update it myself. however i get double tooltips. Is it possible to give me info what i do wrong?

**Comment by MrJul** [comment]
@DimitarCC There have been somes changes in ReSharper 2016.3 regarding how tooltips are handled. See daa0f719965a087f6cf2eb9650b38f2696976998

**Comment by MrJul** [comment]
Enhanced Tooltip 2.10 is now available for ReSharper 2016.3 RTM.
VS2017RC hasn't been tested though, and won't be officially supported by Enhanced Tooltip until VS 2017 RTM.

**Comment by DimitarCC** [comment]
Thanks!
