### ISSUE TITLE
Resharper 2017.1 EAP

### ISSUE THREAD

**Issue by NN---** [MrJul/ReSharper.EnhancedTooltip#97]
Please add support for 2017.1 EAP.
VS 2017 is going out soon and no big changes are planned, you should add support there too.

**Comment by MrJul** [comment]
Expect support for the EAP (or release if it's ready) of ReSharper 2017.1 when VS2017 is released.

**Comment by MrJul** [comment]
v3.0.1-EAP4 is now available for ReSharper 2017.1 EAP4.
